### ISSUE TITLE
Support more versions of python

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#101]
Right now we only support Python 3 (and probably really only Python 3.3+ or something like that.) It may not be easy to support multiple versions of Python in a single code base; for example, the finder/loader system may not be available very far back. In this case perhaps we should just have two version of the tool.
---
- Bitbucket: https://bitbucket.org/austin_bingham/cosmic-ray/issue/3
- Originally reported by: [austin_bingham](http://bitbucket.org/austin_bingham)
- Originally created at: 2015-02-04T12:59:08.661

**Comment by DRMacIver** [comment]
FWIW, I think being Python 3 only is entirely reasonable for source transformation tools. Python 3.2 support would be nice because that's the latest version pypy supports (even if it *is* a horrible limited version of the language)

**Comment by abingham** [comment]
Yeah, I'm not really motivated to support Python 2. I think I'd only consider that if I got a lot of feedback from users that wanted it. 3.2 is probably a good idea, though.

**Comment by jonafato** [comment]
Feel free to disregard the following, as it is just an opinion. 3.2 support is likely not worth it. Per [this recent report](https://caremad.io/2015/04/a-year-of-pypi-downloads/):

> For authors wondering what versions of Python 3.x they should support, it’s easy to make the argument that targeting 3.4, or at the very least 3.3 is a completely reasonable target given that 3.2 (and to a lesser extent, 3.3) have a very tiny marketshare which very likely mostly consists of automated CI systems.

The linked stats show a < 0.5% install rate for Python 3.2 packages, and a substantial majority is coming from 3.4. This is not to say that users of 3.2 are not important, but support probably shouldn't take precedence over development of the project on other fronts, especially as users upgrade to current versions.

**Comment by abingham** [comment]
Probably a reasonable first step here would be to figure out *which* versions of Python3 already work for CR :)

**Comment by degustaf** [comment]
I just made a pull request (#163) that should help with this.  travis is now running tests for Python 3.3 and newer, and the Python 3.3 tests are allowed to fail.

**Comment by atodorov** [comment]
@abingham based on the comments in #163 and #165 I think we can safely close this issue. Python 3.2 and 3.3 support doesn't appear to be possible (at least not easily) and maybe not even desirable at this moment.

**Comment by abingham** [comment]
I agree.

**Comment by snarfed** [comment]
fwiw, I'd love Python 2 support. I've been thinking for a while about how to run this on a few packages and projects i own that are Python 2 only because they run on App Engine (and not its "flexible" environment, which supports Python 3).

i started to port them all to support both 2 and 3, but stopped when i realized the App Engine SDK, which my tests depend on, is 2 only.

i might look into backporting cosmic-ray to 2, since 2 still has the `ast` module, but I'm guessing it's substantially different.

feedback is welcome!

**Comment by abingham** [comment]
@snarfed My guess is that you're right about `ast` in that the biggest Python2/3 differences will come from there. I don't think we do anything in the rest of the CR system that are terribly dependent on Python 2. We may use some Python3-specific syntax here or there, but we could probably massage those to be compatible with both versions.

In principle, the AST differences should be confined to operators. And since those are loaded dynamically as plugins, we should be able to keep Python 2 and 3 separate by simply having two sets of plugins. In practice we may find that we have some abstraction leakage, so to speak, but we could work to plug those holes as part of an effort to support Python 2.

If you've got the time and energy to do the main work on a Python 2 port, I'll do what I can to support you. Where I'd start is by translating one of the existing operators to Python 2 and see how it goes.

**Comment by DRMacIver** [comment]
Note the existence of [astroid](https://pypi.python.org/pypi/astroid/), which will probably go a long way towards papering over the AST differences between Python 2 and 3.

**Comment by abingham** [comment]
Yes, astroid has been on my list of things to look at for quite some time. Maybe this is the kick in the pants we need.
