### ISSUE TITLE
Testing code that use multiprocessing

### ISSUE THREAD

**Issue by Zitrax** [sixty-north/cosmic-ray#110]
Just tried this out so excuse me if I missed something. But when run under cosmic ray all of my tests fail with:

`AssertionError: daemonic processes are not allowed to have children`

And I think this is because python do not support a multiprocessing pool to start up another processing pool.

Would it then make sense to add a switch to run cosmic-ray in a single process ? I know it will be slow but better than not working at all.

And something related; since all of the tests fail you will report a survival rate of 0.00%. Would it make sense that if a first run without any mutations running in the same environment must pass ? Or some warning about tests failing even on non mutated code.

**Comment by abingham** [comment]
That's a really good point. As you say, it sounds like we need some way to run the tests without multiprocessing. In some ways `multiprocessing` is just a convenience; perhaps I can still get some concurrency by  more directly managing subprocess.

Regarding your second issue, this is an area that's open for a lot of work. I *would* generally expect all tests to pass on un-mutated code, and we could check for this as part of the optional baselining pass. I think I'll make a separate issue for this.

Thanks for your feedback. I don't have a whole lot of time to devote to Cosmic Ray right now, but your input is really appreciated. And of course if you feel like making any modification yourself, I'd be happy to work with you on that!

**Comment by abingham** [comment]
I'm working right now on a new version of cosmic ray that should work better with multiprocessing code. The new version distributes tasks using celery, and each testing run is executed in a standalone process. Multiprocessing will not be involved at all. Hopefully that'll be ready for general use in the next few weeks. You can see the work-in-progress on [the celery branch](https://github.com/sixty-north/cosmic-ray/tree/celery).

**Comment by abingham** [comment]
This celery branch is shaping up pretty nicely if you want to give it a try. It should avoid the `multiprocessing` problems you ran into.

**Comment by abingham** [comment]
This stuff ought to work pretty well now, I think, so I'm going to close this out. If you still have problems with CR on multiprocessing code, reopen this and I'll see what we can do.
