### ISSUE TITLE
Purge multiprocessing from the codebase

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#113]
We need to make sure that we never run client code under multiprocessing because client code might itself be using MP and this causes problems. Right now MP is mostly purged, with only the baselining code using it.

**Comment by abingham** [comment]
Fixed in c652199c514960bac50a96066d54f6a6eaac38a0

**Comment by abingham** [comment]
> Would you consider bringing back multiprocessing for local runs?
>
>A developer that is trying to run mutation testing on their Python package should be able to evaluate whether that will cause trouble or not.

I'm not sure I understand the motivation for bringing multiprocessing back. We only used it for running the baseline timing run. What do you expect to gain by bringing it back?

> Further the current set-up process for distributed runs seems far too complex for single-machine unit-testing then it should be.

You're probably right.

> Please consider the example of pytest with it's pytest-xdist plugin or Tox with the detox wrapper.

I know very little about this, but a quick scan of the pytest-xdist documentation makes it sound like I can enable all of the xdist functionality through command line arguments to pytest. Cosmic Ray already allows you to specify arbitrary arguments to pytest. What's stopping you from using pytest-xdist right now?

**Comment by abingham** [comment]
> but wouldn't it be more efficient to parallelize the mutations instead of just the tests

That's an interesting question. My guess is that you're right for most test suites, and that's why we've got the celery-based approach.

> Would something like multiprocessing.Pool() work for CR?

Not in general. If we have several subprocesses executing the same test suite - by which I mean the exact same test code on disk - there are any number of ways they could conflict with one another. CR can't assume hygienic, side-effect-free test suites; it has to assume that they will do interesting things like write to a file in a fixed location or something like that, and in that case they would interfere with one another. IIRC, multiprocessing was a very early approach we tried.

It *would* be great if we could get purely local execution to use all of the cores in a maximally efficient way. That would require doing something like is done with xdist, i.e. making copies of the code. Unfortunately this is not very high-priority for me right now, and I don't have huge amounts of time to devote to CR at the moment.

**Comment by medecau** [comment]
>IIRC, multiprocessing was a very early approach we tried.

I believe you're referring to this: https://github.com/sixty-north/cosmic-ray/blob/cdb0e49166c9e15f8927d82c3234ca254718727b/experiments/notes.md

> Unfortunately this is not very high-priority for me right now, and I don't have huge amounts of time to devote to CR at the moment.

Would you then consider investing a bit on a "Contributing" page that could help newcomers get their heads around the codebase? 🙏
