### ISSUE TITLE
Add better support for displaying testing results.

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#117]
Right now we just dump a bunch of JSON to the screen. This is fine for now, but we probably need a more well-thought-out system for storing results and post-processing them e.g. to display a summary of detection rate.

**Comment by drorasaf** [comment]
I would like to contribute, if you don't mind.

Which type of reporters should it support?
1. json 
2. xml - junit like?
3. any other interesting format?

Should I create a pull request for this one?

**Comment by abingham** [comment]
> I would like to contribute, if you don't mind.

Of course we'd be delighted to get any help you can give!

> Which type of reporters should it support?

This is good question, and I don't have a great answer right now. I think a JSON dump might be a great start, and it should be nearly trivial. We currently store our results in JSON, so getting that to the screen should be easy. An XML/JUnit reporter might be useful, but I don't really know; we'd have to think about how it would be used.

More generally, I think the first problem to solve is making an extensible reporting system. We currently have plugin systems for our mutation operators and test runners; it might make sense to have a similar system for report generators. Our current 'report' command implementation would just be one implementation of this plugin, and we could make plugins for JSON, JUnit, HTML (which might be *very* useful), and anything else we want.

There's another approach to report extensibility that might be better, though. CR could support one basic "dump" command that would print a JSON format to stdout. Then other reports could just consume that JSON to create whatever reports they want. This would simplify the infrastructure inside CR, and it would mean users could use any tool/language they wanted for generating final reports.

**Comment by atodorov** [comment]
> I would like to contribute, if you don't mind.

We certainly don't mind but do you have a particular use case? I understand the desire to contribute and get your hands dirty with the code but unless there is a practical need we shouldn't really bother with that. I would rather have more mutation operators and make CR more usable instead of having better reports. If you are up for a challenge PM me (email, twitter, IRC, whatever).

**Comment by drorasaf** [comment]
My practical need is to use it as part of continuous integration cycle, specifically with Jenkins, the easiest integration with it is by using xml/Junit format as far as I know

**Comment by abingham** [comment]
The more I think about this, the more I like the idea of replacing "report" with a simple JSON dump command. Then we (or anyone) could easily create other extrinsic programs that parse this JSON and convert it to other forms. What I'm imagining is something like `cosmic-ray json`, and the analog for our current report command might be `cosmic-ray json | cr-report` where `cr-report` could be provided by cosmic-ray.

**Comment by drorasaf** [comment]
Isn't json in the pipe redundant if there is only one default output?
Maybe `cosmic-ray report | cr-report` to provide more information on what this phase does?

**Comment by abingham** [comment]
> Maybe cosmic-ray report | cr-report to provide more information on what this phase does?

The point here is that `cosmic-ray report` would produce a single, canonical JSON output. CR would not produce any other form of report. Then other programs, e.g. the notional `cr-report`, would consume that JSON and produce whatever other kind of output was needed. So imagine `cr-report` as taking the CR JSON output and converting it into the JUnit format you want.

The logic of this approach is that JSON is easy to generate, and it's easy to consume in practically any language. So we make it relatively easy for people to create whatever reports they need without unnecessarily complicating the CR internals.

**Comment by drorasaf** [comment]
I agree with this approach. just one last little thing, why run/exec does not provide the output and another step(report) is mandatory?

**Comment by abingham** [comment]
> why run/exec does not provide the output and another step(report) is mandatory?

The main reason is basic software design principles: separation of concerns. In many cases a user might be satisfied with getting a reports as a result of an exec, but not always. More importantly, they need to be able to generate the report at any time after the exec, often more than once. If we tied report generation directly to exec then they'd need to re-run (a potentially empty) exec.

**Comment by drorasaf** [comment]
For some unknown reason, most of the testing frameworks I have came across, still use the old fashioned redirection if necessary to provide consistency.
For example, other mutation testing frameworks, stryker and pitest provide the output to stdout/stderr

**Comment by abingham** [comment]
CR provides report output to stdout/stderr as well; we just don't do it as a direct result of exec. I think it's a pretty practical system, which is probably why the other systems you mention do the same thing. But maybe I'm missing your point.

**Comment by drorasaf** [comment]
I have an implementation for xml output.
few questions before the pull request:
1. currently it is named cr-xml, any preferences on the naming?
2. Where should the implementation reside? currently I just added it to format.py
3. The implementation uses the following syntax: cosmic-ray dump example | cr-xml > output.xml
Should it be redirected or part of the arguments?or just create cr.xml file?
4. I integrate it currently with basic JUnit output, I saw there is a dedicated jenkins plugin for PIT, should we prefer to integrate with it?

**Comment by abingham** [comment]
> 1. Currently it is named cr-xml, any preferences on the naming?

That sounds fine to me. The only alternative that comes to mind is integrating the XML output into cr-report as an optional output format, but I can't come up with a great motivation for that right now. Let's just keep things like they are.

> 2. Where should the implementation reside? currently I just added it to format.py

I think that's fine for now. We'll probably refactor where all of those tools live at some point when it's more clear what we should do.

> 3. The implementation uses the following syntax: cosmic-ray dump example | cr-xml > output.xml
> Should it be redirected or part of the arguments?or just create cr.xml file?

I definitely prefer that the tool has the option to write to stdout, and I generally like that to be the default behavior. But if you want to add a command line flag that writes output to a file, I'm fine with that.

> 4. I integrate it currently with basic JUnit output, I saw there is a dedicated jenkins plugin for PIT, should we prefer to integrate with it?

I guess I don't know enough about the issue to make a truly informed decision right now. JUnit integration sounds like a good thing. 

I'm not opposed to a Jenkins plugin, but it should probably be in a separate repository.

**Comment by abingham** [comment]
I think this issue is largely taken care of. Or at least, any residual work for it should be taken up in separate issues. At the PyConUK sprint there was some work on better junit integration, and hopefully that'll make its way into the repo at some point.
