### ISSUE TITLE
add "locate" command

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#138]
It would be nice to have a command like `cosmic-ray locate <module name> <operator> <occurrence>` which would print the filename and line number (and possibly the actual code and some context) where the mutation took place. This would make it easier to zero in on issues for users.

**Comment by atodorov** [comment]
@abingham I think we have resolved this by introducing the diff report syntax. I can see the value of the locate command but frankly I can't think of any other use-case except seeing the actual mutation when stuff goes wrong.

Otherwise this should be easy to implement.

**Comment by abingham** [comment]
@atodorov You're right, the need for the locate command has evaporated. I'll close this out.
