### ISSUE TITLE
TypeError: 'float' object is not subscriptable on a large JSON file

### ISSUE THREAD

**Issue by atodorov** [sixty-north/cosmic-ray#148]
I'm running cosmic-ray against pykickstart (the whole package) and after the execution was complete I've tried running the report. It printed the first 340 jobs and the hit a traceback:

```
Traceback (most recent call last):
  File "/home/atodorov/.virtualenvs/pykickstart_docs/bin/cosmic-ray", line 11, in <module>
    sys.exit(main())
  File "/home/atodorov/.virtualenvs/pykickstart_docs/lib/python3.5/site-packages/cosmic_ray/cli.py", line 361, in main
    sys.exit(handler(sub_config))
  File "/home/atodorov/.virtualenvs/pykickstart_docs/lib/python3.5/site-packages/cosmic_ray/cli.py", line 204, in handle_report
    for line in cosmic_ray.commands.create_report(db, show_pending):
  File "/home/atodorov/.virtualenvs/pykickstart_docs/lib/python3.5/site-packages/cosmic_ray/commands/report.py", line 43, in create_report
    yield from _print_item(item)
  File "/home/atodorov/.virtualenvs/pykickstart_docs/lib/python3.5/site-packages/cosmic_ray/commands/report.py", line 15, in _print_item
    ret_val.extend(result[1][1])
TypeError: 'float' object is not subscriptable
```

NOTE: this is with my patch from #145 but that shouldn't matter. I'll attach the json file if I can.

**Comment by atodorov** [comment]
[pykickstart.json.zip](https://github.com/sixty-north/cosmic-ray/files/352095/pykickstart.json.zip)

**Comment by abingham** [comment]
Interestingly, I'm seeing this as well on cosmic-ray's own test suites. I'll try to get to the bottom of is soon.

**Comment by abingham** [comment]
The problem seems to be that we're not properly handling timed-out tests in the reporting module. In `command.report._print_item()` we need to check if `item.result_type` is `"timeout"`. If so, then `item.result_data` will be a float indicating the amount of time spent running the test. This should be simple to fix.

**Comment by abingham** [comment]
@atodorov This bug appears to be a problem with your diff-based reporting patch. You're not taking into account the different kinds of values that might be present in `item.result_data` in `commands.report._print_item()`. 

I'll admit that the data structures in CR have developed a bit haphazardly. There is, for example, no good documentation for how `WorkItem` is shaped...it's just a named tuple. It might be time to revisit it.

As things are, though, I'm going to close this issue and move the work/discussion over to the patch. If I'm wrong in my analysis, we'll just reopen this.
