### ISSUE TITLE
AND/OR replacement notes - consecutive operations with the same operator produce a single mutation

### ISSUE THREAD

**Issue by atodorov** [sixty-north/cosmic-ray#170]
Consider the expression `condA and condB` which is mutated into `condA OR condB` - this is as expected. Now consider a more complicated expression: `condA and condB and condC`. You may expect that there will be two mutations here:
`condA OR condB and condC` and 
`condA and condB OR condC`, a bonus mutation may be considered as well
`condA OR condB OR condC`

However this is not the case. Only the last mutation is produced!  Consecutive operations with the same operator, such as `a or b or c`, are collapsed into one node with several values. See the example below
```
>>> ast.dump(ast.parse('meat and bread'))
"Module(body=[Expr(value=BoolOp(op=And(), values=[Name(id='meat', ctx=Load()), Name(id='bread', ctx=Load())]))])"
>>> 
>>> ast.dump(ast.parse('meat and bread and mayo'))
"Module(body=[Expr(value=BoolOp(op=And(), values=[Name(id='meat', ctx=Load()), Name(id='bread', ctx=Load()), Name(id='mayo', ctx=Load())]))])"
>>> 
>>> ast.dump(ast.parse('meat and bread and mayo and eggs'))
"Module(body=[Expr(value=BoolOp(op=And(), values=[Name(id='meat', ctx=Load()), Name(id='bread', ctx=Load()), Name(id='mayo', ctx=Load()), Name(id='eggs', ctx=Load())]))])"
```

@abingham this is documented at http://greentreesnakes.readthedocs.io/en/latest/nodes.html#BoolOp but I've missed it somehow. Where do you think is the proper place in Cosmic Ray to add a warning about this behavior ?

**Comment by abingham** [comment]
Interesting. With the current design, we probably need to update our operators and mutating core a bit to account for nodes like this. Roughly, I'm picturing something like this:

1. `Operator.visit_mutation_site()` needs to accept a new `count` argument indicating how many mutations can be made by an operator on a particular node. It will forward this new parameter along to the cores' `visit_mutation_site()`s (which also need to be updated).
2. The `Visit_*()` methods on operators need to pass this new `count` parameter when they call `visit_mutation_site()`. So in this case the operator will need to see how long the `values` field of the `Expr` node is and use that to determine `count`.
3. `Operator.mutate()` will accept a new `count` argument indicating which of potentially multiple mutations to make.
4. When `MutatingCore.visit_mutation_site()` is looping through nodes, it needs to account for this new `count` and pass along the right number to `mutate()`.

I don't think any of this is particularly complex, just a bit tedious. How does that sound to you, @atodorov?

**Comment by atodorov** [comment]
Sounds relatively easy to do. I will have to experiment with the code a bit and see how it goes. That will probably be next week though. 

I was thinking about another approach - visit the nodes which are part of the current expression (e.g. compare their parent with the `and` operator we're trying to mutate) and mutate the node accordingly. Anyway let me get back to you once I have a few hours to play with this and see how it goes.

**Comment by atodorov** [comment]
@abingham here's an almost working implementation of what you suggested. I'm having a small problem though. The refactored code for AND replacement successfully replaces the AND operator in all places one by one (or at once). However then we replace the 1st or the last operator I get the error below. The problem is that newly created AST nodes are missing lineno and col_offset attributes and Python can't compile the entire tree in this case. I thought `ast.fix_missing_locations()` will fix it but no.

Also note that this doesn't fail when replacing an operator in the middle of the expression. For example
`A and B and C and D` -> `A and B or C and D` compiles just fine.

```
command: cosmic-ray worker sandwich replace_and_with_or 2 nose -- -v tests.py
Traceback (most recent call last):
  File "/home/senko/.virtualenvs/CosmicRay/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/senko/.virtualenvs/CosmicRay/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/senko/.virtualenvs/CosmicRay/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/senko/.virtualenvs/CosmicRay/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/senko/.virtualenvs/CosmicRay/lib64/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/senko/.virtualenvs/CosmicRay/lib64/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/mutation-testing-in-patterns/python/example_07/tests.py", line 1, in <module>
    import sandwich
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/senko/.virtualenvs/CosmicRay/lib/python3.5/site-packages/cosmic_ray-1.0.0a1-py3.5.egg/cosmic_ray/importing.py", line 27, in exec_module
    exec(compile(self._ast, self._name, 'exec'),  # pylint:disable=exec-used
TypeError: required field "lineno" missing from expr

--- mutation diff ---
--- a/tmp/mutation-testing-in-patterns/python/example_07/sandwich.py
+++ b/tmp/mutation-testing-in-patterns/python/example_07/sandwich.py
@@ -25,5 +25,5 @@
     def __eq__(self, other):
         if (not other):
             return False
-        return ((self.meat == other.meat) and (self.bread == other.bread) and (self.mayo == other.mayo) and (self.eggs == other.eggs))
+        return ((self.meat == other.meat) or ((self.bread == other.bread) and (self.mayo == other.mayo) and (self.eggs == other.eggs)))
 ```

**Comment by abingham** [comment]
That's an interesting problem. I don't know off the top of my head why this is happening, though I will say that maintaining line numbers and stuff in AST seem to be consistently difficult. I'll see if I can sort it out.

This might be another indicator that we should investigate astroid or some other ast tools.

**Comment by atodorov** [comment]
Just FYI, I have resolved the problem mentioned above. At the time I wrote the comment I was passing a single BoolOp node to the values argument, not a list. Everything is fine now.

I've also added a commit which uses ast.fix_missing_locations instead of ast.copy_location and that should solve the case once and for all (let's hope).
