### ISSUE TITLE
Use new multi-mutation support to clean up rel-op replacement operators

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#173]
As discussed in [PR 172](https://github.com/sixty-north/cosmic-ray/pull/172), now that operators can perform multiple mutations per node, this might give us the opportunity to clean up relational-operator replacement operators. Right now we dynamically generate a whole bunch of classes to do all the kinds of mutations we might want (i.e. effectively the cartesian product of relational operators). This is a bit obscure and weird.

The alternative is to have rel-op replacement operators report that they can perform multiple replacements, one for every other kind of rel-op.

**Comment by atodorov** [comment]
Just FYI, this is on my todo list next.
