### ISSUE TITLE
Timeout measurement mismatch

### ISSUE THREAD

**Issue by atodorov** [sixty-north/cosmic-ray#182]
Filing here so it doesn't get forgotten:

https://github.com/sixty-north/cosmic-ray/pull/181#discussion_r86957480

> I'm a little bit concerned since the baseline is now timing one thing - the time to run the tests - while the worker is timing something else - the time to start a python process and run the tests. This is probably not a practical issue for most cases, but it's worth keeping in mind.

To clarify this:
- after the latest changes (#181) we measure the baseline as the time it takes to execute the test suite, but don't take into account starting the Python process, loading modules, etc.
- the worker however starts a new process before running tests on the mutants. In case we hit an endless loop or the task takes too long the process is killed. 

There will be a slight difference in how times are measured. I don't think it is a problem with timeout multiplication factor of 10 (as documentation suggests), e.g. if it takes 10 times longer to execute tests against the mutant compared to baseline then kill it.

**Comment by abingham** [comment]
This appears to be an actual problem in practice now.

**Comment by abingham** [comment]
This is fixed in 54e2424dcb74f01d1b0b040f873d538386107ef0
