### ISSUE TITLE
Ran the following testsuite and cosmic-ray is reporting 100% survival rate

### ISSUE THREAD

**Issue by cynthia-rempel** [sixty-north/cosmic-ray#185]
Used cosmic-ray on the following test-suite and reported 100% survival-rate.
Using Python 3.5.2
cosmic-ray was reporting a lower survival rate percentage before I added test-cases, but after it continued to report 100% survival rate reinstalled directly from version-control, and still no dice...
[test_waveforms.zip](https://github.com/sixty-north/cosmic-ray/files/645191/test_waveforms.zip)

**Comment by abingham** [comment]
Just looking at it, I think the essential problem is that your tests are in the same module as your code-under-test, i.e. it's all in test_waveforms.py. This is (currently, at least) a problem for cosmic ray since it will try to mutate *everything* it can in the modules that you point it at. So I think what's happening is that CR is mutating not only the functions like `chirp_linear` etc, but also the code in `TestChirp`, `TestSweepPoly`, etc. Even if this doesn't account for the 100% survival rate, it's going to produce some very bad results.

I'll take a try at separating the test code from the production code and see if I can get some reasonable results. You might try the same thing, and we can compare notes.

**Comment by abingham** [comment]
BTW, I know that this unexpected behavior isn't really documented anywhere. Sorry about that.

**Comment by abingham** [comment]
I've [made a go at splitting the test and production code] (https://github.com/sixty-north/cosmic-ray/files/645281/test_waveform.fixed.zip). Basically, all of the production code is in `wf.py` and the tests remain in `test_waveforms.py`. I was getting a 13.39% survival rate after the split. The results are in `verify.fixed.json`.

You can view the results yourself with:
```
cosmic-ray report verify.fixed
``` 

If you want to try replicating the results use:
```
cosmic-ray init --baseline=3 verify.local wf -- .
cosmic-ray exec verify.local
cosmic-ray report verify.local
```
(replacing "verify.local" with whatever session name you want).

Let me know if helps or just confuses things even further.

**Comment by abingham** [comment]
@cynthia-rempel Any luck with this?

**Comment by cynthia-rempel** [comment]
Hi,
Thanks for following up on this so quickly and persistently, I will run it
again tonight :)
You're amazing!

**Comment by cynthia-rempel** [comment]
I moved scipy/scipy/signal/waveforms.py to the ~/fixed directory, changed 
import scipy.signal.waveforms as waveforms
to 
import waveforms as waveforms
and am running

cosmic-ray init --baseline=3 verify.local waveforms -- .
cosmic-ray exec verify.local
cosmic-ray report verify.local

using the separate wf code...

**Comment by abingham** [comment]
Are you getting some reasonable results now? Assuming that we made equivalent changes (i.e. you moved your tests out of waveform.py) I would expect you to be getting the same survival rate I got.

This is all really valuable feedback for Cosmic Ray, btw, and I really appreciate it. Seeing how someone is using the tool in practice is critical for us. Thanks!

**Comment by abingham** [comment]
> changed
> import scipy.signal.waveforms as waveforms
> to
> import waveforms as waveforms

As a side note, `import waveforms as waveforms` is exactly the same as simply `import waveforms`.  Functionally it's fine to leave it as it is, but it would be more "pythonic"/idiomatic to use the simpler form.

**Comment by cynthia-rempel** [comment]
After letting the tests run all night, I killed the process and got:
total jobs: 877
no jobs completed
Trying:
celery -A cosmic_ray.tasks.worker worker&

**Comment by cynthia-rempel** [comment]
Got a report... Not sure if I believe it though...
total jobs: 877
complete: 877 (100.00%)
survival rate: 0.00%

Will start removing additional tests to see which tests were actually needed...

**Comment by abingham** [comment]
Hmmm, yeah, that's a bit suspicious. If you add a simple test that always passes trivially, do you get the same results? 

If you run `cosmic-ray report --full-report <session-name>` it'll print all of the mutations that it made. You could pick one of them, make the mutation yourself, and see if the tests actually pass when you run them manually.

It's also possible that there's some problem running the tests on the worker, something that causes the tests to appear to kill the mutant. You can run the worker with more logging like this:
```
celery -A cosmic_ray.tasks.worker --loglevel=info worker
```
This might reveal something useful.

**Comment by abingham** [comment]
By the way, there's a new, simpler mode for running CR on [the `local-exec` branch](https://github.com/sixty-north/cosmic-ray/tree/local-exec). This one doesn't rely on celery or distributed workers by default (though it can run in that mode if you want). For a project of your size it might be more convenient. It should be functionally just as good as the master branch.

**Comment by cynthia-rempel** [comment]
Looks like it's timing out...
[full_report.txt](https://github.com/sixty-north/cosmic-ray/files/658456/full_report.txt)

**Comment by cynthia-rempel** [comment]
For grins, I changed --baseline to 100
killed it after ~100 tests, said the survival rate was 13.08%, which is more believable...

cosmic-ray init --baseline=100 verify.local waveforms -- .
cosmic-ray exec verify.local
celery -A cosmic_ray.tasks.worker --loglevel=info worker&
cosmic-ray report verify.local

**Comment by cynthia-rempel** [comment]
Looks like it worked with: 

cosmic-ray init --baseline=100 verify.local waveforms -- .
cosmic-ray exec verify.local
celery -A cosmic_ray.tasks.worker --loglevel=info worker&
cosmic-ray report verify.local

I really like how the --loglevel=info shows progress, and I never knew the --full-report could show which test killed which mutant!

total jobs: 877
complete: 877 (100.00%)
survival rate: 14.03%

[report.txt](https://github.com/sixty-north/cosmic-ray/files/658525/report.txt)

**Comment by abingham** [comment]
Great! It sounds like things are working reasonably now. (Sorry for the late response...still catching up with real life after the holidays.) 

Thanks again for working through all of this. This kind of feedback is vital for making CR better.
