### ISSUE TITLE
Create celery4 execution engine plugin

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#189]
It looks like there's a new Celery 4 major version that we should at least look at. I've pinned the version we use to <4 for now.

**Comment by proggga** [comment]
Yea, I work with celery4 and cant test my celery task by this tool, becouse cosmic-rays requires "The 'celery<4' distribution was not found and is required by cosmic-ray", but if I install celery.3.1.15 test doesnt works

**Comment by abingham** [comment]
Hopefully I can get to this fairly soon. I don't remember the details, but I seem to recall that the API changed some between Celery 3 and 4, so the main work in upgrading will probably involve just dealing with those changes.

Ultimately, I'd like to be able to support both. I have a rough plan to make a plugin system for "executors" which would determine how tests were distributed and executed. Right now we have to executors internally, "celery" and "local", but there's no extension system for adding more.

If we could make an extension system that let plugins define their own dependencies (e.g. celery-3 or celery-4), then it should be very easy to support both versions. I don't think any of this represents a huge amount of work or complexity.

**Comment by abingham** [comment]
We've finally had time to separate the celery3 engine into its own plugin, so now we've got leeway to create a celery4 plugin as well.

**Comment by proggga** [comment]
I have not free time, but it very good news! Your great. You can feel my support on your ideas =0
