### ISSUE TITLE
Create plugin system for execution modes

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#192]
Right now we have two execution modes, local and celery. In principle we could have many more. I'd like to create a plugin system that abstracts the notion of "execution context", of which celery and local would be the first two examples. This would work similar to how the test runner plugins work.

Related to this, we'll probably need a more sophisticated configuration system (probably based on .ini files or something similar) so that our various plugins can have plugin-specific configuration. See #193 for  more details.

**Comment by benjiman** [comment]
Lhmkh

**Comment by abingham** [comment]
#189 give some good motivation for this. We ultimately need executors for different versions of celery since some clients will have their own celery version dependencies.

**Comment by abingham** [comment]
Fixed in 985e9c680d9031121c856c912960dd93fbf55595
