### ISSUE TITLE
Create a better configuration system

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#193]
Right now our configuration options are limited to command line options. This presents a real problem when it comes to our expanding ecosystem of plugins because each type of plugin (test runners, execution contexts, possibly even operators) will need some level of configuration.

I think the simplest approach is to support configuration via .ini files. We can then use the sections of .ini files to let each plugin get its own configuration details. This configuration data will be made available to the entire program, perhaps just by having a global variable.

The first place to test this out is with the celery execution mode. It will need configuration options such as "purge_queue" and the various parameters for connecting to the rabbitmq server.

**Comment by drorasaf** [comment]
I would suggest using .yaml over .ini, more robust.

**Comment by abingham** [comment]
> more robust

How so? I don't necessarily disagree, but any concrete arguments one way or the other will be useful.

**Comment by abingham** [comment]
This has been effectively fixed by the recent switch to configurations/sessions. Our configuration files are all YAML.
