### ISSUE TITLE
Improve the data structures used to pass status info

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#207]
The data structures used to pass status info around in CR are confusing. We have overlapping terminology, special-case tuples that we have to handle carefully, and other stuff that makes it more difficult than necessary to see what's going on.

I've created [the `better-data-structure` branch](https://github.com/sixty-north/cosmic-ray/tree/better-data-structure) to try to improve the situation.

@atodorov Could you take a look at this and let me know what you think? You're really the only other person with any amount of CR development time, so your feedback would be helpful. I think the new WorkRecord cleans up quite a bit of the confusion in the codebase, but I may be missing the mark.

**Comment by atodorov** [comment]
@abingham I will review it over the weekend

**Comment by abingham** [comment]
Thanks. There's no rush on it. It is really the yak-shaving that started
when I tried to do something else (improve the error handling of the worker
subprocess) and found the task overly-complex.

**Comment by atodorov** [comment]
@abingham a few comments besides the ones in the actual commits:

1) cosmic-ray report --full-report:
```
job ID 4cf2daf0335b11e7b40234363b8604e2:timeout:adam
command: cosmic-ray worker adam replace_and_with_or 1 unittest -- tests
timeout: 0.149 sec

job ID 4cf2dc08335b11e7b40234363b8604e2:timeout:adam
command: cosmic-ray worker adam number_replacer 0 unittest -- tests
timeout: 0.149 sec
```

- Job ID is all the same and I really don't like the hash. Kind of takes away the notion of progress.
- Also no diff reported which is a regression (and we really need a test for it)

2) You really need to add better commit logs or more comments in the code so it is clear what do you intend to do. Honestly I'm not quite sure I follow you through the code. Maybe explain the whole refactoring idea here so I can get a better understanding of it.


Overall I think your changes are OK, they add more structure and given the late hour I was still able to mostly follow the code. IMO let's go ahead but make sure to fix the regression at least.

**Comment by abingham** [comment]
I apologize for the lack of comments and spotty commit log; a lot of this was done at airports/on airplanes in burst of a "free time", and I was a bit lazy. Thanks for looking through it all despite the shortcomings.

The fundamental idea of this commit (which you've clearly sorted out on your own by now) is to use a single data structure - the `WorkRecord` - for passing work and work-in-progress around the entire CR infrastructure. Importantly, this will make the code terminologically consistent (i.e. we won't overload the term "outcome" and "result" as we were).

**Comment by abingham** [comment]
> Job ID is all the same and I really don't like the hash. Kind of takes away the notion of progress.

I was certainly hesitant to use UUIDs like this, but they (or something like them) seem like the best overall answer. My experience is that tying the unique IDs of entities like our work records to specific database details is a mistake in the long run. UUIDs let us decouple the creation of work-records from most other choices in the system.

You're right that the job-ids are all (almost) the same. The `uuid1()` function was creates very similar-looking IDs, so I'll switch to `uuid4()` which is more "random".

**Comment by abingham** [comment]
> Also no diff reported which is a regression (and we really need a test for it)

I've fixed this, and I'll create an issue for testing for diffs in the output. Maybe just a simple approval test will suffice.

**Comment by abingham** [comment]
@atodorov Thanks so much for your help reviewing this change. It's immensely helpful to have someone like you helping out on this project.
