### ISSUE TITLE
How to find the exact test that kills a mutant

### ISSUE THREAD

**Issue by Caitlynn** [sixty-north/cosmic-ray#213]
Hi, I am doing some research in mutation testing and I'm just wondering if it's possible for me to find the exact test case that killed which mutant. 

I have went through the code several times, and I have got no clue. Could you please help me?

**Comment by abingham** [comment]
If you're using pytest then you should be able to see the test that kills a mutant with `cosmic-ray report --full-report <session-name>`. You'll see output like this:
```
job ID 69e7e608a2204d1ea05209b447d32de7:killed:adam
command: cosmic-ray worker adam mutate_comparison_operator 2 pytest -- -x tests
<TestReport 'test_project/tests/test_adam.py::Tests::test_equals' when='call' outcome='failed'>
```
The `TestReport` bit tells you the failing test.

Unfortunately it looks like the unittest test runner is broken in this respect. It's not reporting anything useful. I need to look into that.

**Comment by Caitlynn** [comment]
Thank you so much for your help! Could you also please let me know when you fix the broken part?

**Comment by abingham** [comment]
Actually, I've done some poking around this morning, and it looks like unittest test runner actually works just fine. The issue is that timeouts are little bit broken. Issue #182 actually deals with this.

Try increasing your `--baseline` to 10 or 100 times whatever you're using now. This will give your mutation test runs more time to complete. Assuming your tests are now able to finish (i.e. not timeout), `cosmic-ray report --full-report <session-name>` for unittest-based tests will look something like this:
```
job ID 52d12b87cb014fc39ca09a2c71957f0d:killed:adam
command: cosmic-ray worker adam zero_iteration_loop 2 unittest -- tests
Traceback (most recent call last):
  File "/Users/sixtynorth/projects/sixty-north/cosmic-ray/test_project/tests/test_adam.py", line 76, in test_single_iteration
    self.assertTrue(adam.single_iteration())
AssertionError: None is not true

--- mutation diff ---
--- a/Users/sixtynorth/projects/sixty-north/cosmic-ray/test_project/adam.py
+++ b/Users/sixtynorth/projects/sixty-north/cosmic-ray/test_project/adam.py
@@ -66,7 +66,7 @@
 def single_iteration():
     result = None
     iter = [object()]
-    for i in iter:
+    for i in []:
         result = True
     return result
```

The traceback tells you where the failure occurred. Let me know if this solves things for you; maybe there's something else going on as well.

**Comment by Caitlynn** [comment]
Thank you so much! It worked well!!

**Comment by abingham** [comment]
Wonderful! I'm glad I could help.

**Comment by disouzam** [comment]
> If you're using pytest then you should be able to see the test that kills a mutant with `cosmic-ray report --full-report <session-name>`. You'll see output like this:
> 
> ```
> job ID 69e7e608a2204d1ea05209b447d32de7:killed:adam
> command: cosmic-ray worker adam mutate_comparison_operator 2 pytest -- -x tests
> <TestReport 'test_project/tests/test_adam.py::Tests::test_equals' when='call' outcome='failed'>
> ```
> 
> The `TestReport` bit tells you the failing test.
> 
> Unfortunately it looks like the unittest test runner is broken in this respect. It's not reporting anything useful. I need to look into that.

Hello, @abingham :

Is there an equivalent command to this command today:

```bash
cosmic-ray report --full-report <session-name>
```
?

I've searched in documentation and I'm also poking with source code (with temporary customizations) and I couldn't find yet.
