### ISSUE TITLE
PyPI out of date (0.1.2)!

### ISSUE THREAD

**Issue by dmhowcroft** [sixty-north/cosmic-ray#228]
Using `pip==9.0.1` under Python 3 and running `pip install --user cosmic_ray` or `pip install --user cosmic-ray` installs cosmic_ray 0.1.2. 

Running `pip install --user cosmic_ray==1.1.0a1` will install that version, however.

If I try installing the current version (2.0.0a0) this way, however, I get the message:

```
$ pip3 install --user cosmic_ray==2.0.0a0
Downloading/unpacking cosmic-ray==2.0.0a0
  Could not find a version that satisfies the requirement cosmic-ray==2.0.0a0 (from versions: 1.1.0a1, 1.0.0a1, 0.1.0, 0.1.1, 1.0.0a0, 1.0.0a0.macosx-10.10-x86_64, 0.1.2)
```

So there seem to be two problems:
1) PyPI is serving an older version of the package rather than the most recent version in its index; and
2) verson 2.0.0a0 has not been added to PyPI yet.

**Comment by abingham** [comment]
Thanks for pointing that out! I've definitely neglected CR a bit lately :( I've pushed 2.0.0 up to pypi, and hopefully it'll get more attention soon. I'm hoping to do a cosmic ray sprint at pycon UK this year!
