### ISSUE TITLE
pip install package is not up to date

### ISSUE THREAD

**Issue by drorasaf** [sixty-north/cosmic-ray#229]
Currently when trying to install package using pip install cosmic-ray the version is 0.1.2
any intentions to change this soon?

BTW, the markdown of the readme does not work properly  on pypi:
https://pypi.python.org/pypi/cosmic_ray/2.0.0a0
consider to use readme.rst

**Comment by abingham** [comment]
> Currently when trying to install package using pip install cosmic-ray the version is 0.1.2 any intentions to change this soon?

Hmmm, this was supposed to have been fixed. I uploaded 2.0.0a0 wheels, source dists, and now an osx binary dist. Any idea why pip doesn't use those?

> the markdown of the readme does not work properly on pypi

I consider that a failing of pypi. If there's a way to create an RST that automatically stays in sync with my markdown, if that technique is not too intrusive, and if someone is willing to put in the work to make it happen, I'm happy to support it. As it is, though, github is the home for my project; pypi is just a distribution channel.

**Comment by drorasaf** [comment]
> Hmmm, this was supposed to have been fixed. I uploaded 2.0.0a0 wheels, source dists, and now an osx binary dist. Any idea why pip doesn't use those?
probably because of the semantic versioning? but I'm not sure.

Regarding using rst: https://github.com/chrissimpkins/md2rst
should be quite simple although I did not use it myself.

**Comment by abingham** [comment]
Right, converting md to rst is generally trivial. But I don't want to
maintain two version of the same file, and converting it for the sake of
pypi is way down my list of priorities. I'd consider a pull request if
you're so inclined, but I really wish pypi would just get with the times.

**Comment by user171** [comment]
Regarding the md / RST format, I don't know your reasons, but if that helps, Github supports RST: https://github.com/github/markup/blob/master/README.md#markups

And I believe it is common to use  RST nowadays for python documentation.

Maybe you only need to maintain the RST version.

My 2 cents.

**Comment by donkirkby** [comment]
In case anyone is new to pip and needs a workaround, you can override the default version with a command like this:

    pip install cosmic-ray==2.0.0a0

Just specify whatever the latest version is, as displayed on [pypi].

[pypi]: https://pypi.python.org/pypi/cosmic_ray

**Comment by abingham** [comment]
@drorasaf Can we close this issue?

**Comment by donkirkby** [comment]
@abingham, I still get version 0.1.2 when I just run `pip install cosmic-ray`, so I suggest leaving this issue open.

**Comment by donkirkby** [comment]
If it's helpful, I ran `pip install` with verbose output:

```
$ pip install -vvv cosmic-ray --no-cache-dir
Collecting cosmic-ray
  1 location(s) to search for versions of cosmic-ray:
  * https://pypi.python.org/simple/cosmic-ray/
  Getting page https://pypi.python.org/simple/cosmic-ray/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/cosmic-ray/ HTTP/1.1" 200 910
  Analyzing links from page https://pypi.python.org/simple/cosmic-ray/
    Found link https://pypi.python.org/packages/11/ac/efed7664affcb04e545b6d613e20bf9543b9603de3158e5c6c01cbc639b4/cosmic_ray-1.1.0a1.tar.gz#md5=289404ec4bc09a4eee21976e9d5b2c23 (from https://pypi.python.org/simple/cosmic-ray/), version: 1.1.0a1
    Found link https://pypi.python.org/packages/30/0d/c2ac8fe461c67d1c7d1be95ffd873805f1a34b12794950178e48a7fd3792/cosmic_ray-2.0.0a0-py3-none-any.whl#md5=5ba7ee2bce3727f8e3305ce5e00a5613 (from https://pypi.python.org/simple/cosmic-ray/), version: 2.0.0a0
    Found link https://pypi.python.org/packages/36/dc/a7f6a5486f22279491dc4f5b886f7cb19b7f413d23c2802a8ec77e80d0b1/cosmic_ray-1.0.0a1.tar.gz#md5=acbaa387a4925c3f442dff39828f0efe (from https://pypi.python.org/simple/cosmic-ray/), version: 1.0.0a1
    Found link https://pypi.python.org/packages/4f/49/b92fc1fcd40d97cf4a45b685a01531e901371e70daa2fcaf3c9fee28cb9e/cosmic_ray-0.1.0.tar.gz#md5=915dfd158fdc39f42edeec1506361629 (from https://pypi.python.org/simple/cosmic-ray/), version: 0.1.0
    Found link https://pypi.python.org/packages/51/59/fedbe5a3d30f1eb5f2170022d247538647af78f3e5359e4ecdbe2a7d82c5/cosmic_ray-2.0.0a0.tar.gz#md5=66a30325bdc83abc0c3df67a5390611d (from https://pypi.python.org/simple/cosmic-ray/), version: 2.0.0a0
    Found link https://pypi.python.org/packages/75/b1/d73bd742c7dbd4cd620ac6b907694a3b63b815adc31a5b5c39c8a3ecb60e/cosmic_ray-2.0.0a0.macosx-10.12-x86_64.tar.gz#md5=7b2b4915b5c8d144ea42c1a22d9321c5 (from https://pypi.python.org/simple/cosmic-ray/), version: 2.0.0a0.macosx-10.12-x86_64
    Found link https://pypi.python.org/packages/7f/38/ad74a127be821da7158eceede2e7e2d73615ddcda6fc7f4347b08de20565/cosmic_ray-0.1.1.tar.gz#md5=4362c409069c00870c0f0369bd5b0b2e (from https://pypi.python.org/simple/cosmic-ray/), version: 0.1.1
    Found link https://pypi.python.org/packages/a4/68/ad55f290efc5bce129ffa251a71011ba3e6e11a0311fcd6a02400f296823/cosmic_ray-1.0.0a0.tar.gz#md5=3f8d2ee646578b51567ce0d0a37a8191 (from https://pypi.python.org/simple/cosmic-ray/), version: 1.0.0a0
    Found link https://pypi.python.org/packages/e3/d9/2fc7b24dfb9475bf3ee0011c51625cd77e24803ed896354d792bdc44d454/cosmic_ray-1.0.0a0.macosx-10.10-x86_64.tar.gz#md5=b32682c185dfa96ab0bc8004be1d5ef7 (from https://pypi.python.org/simple/cosmic-ray/), version: 1.0.0a0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/e4/5d/6415080e6c525b9e4da5d213034166a9eb7c71a012596fa0006a07831dcd/cosmic_ray-0.1.2.tar.gz#md5=53307363e03a4b93569c0f388558ac68 (from https://pypi.python.org/simple/cosmic-ray/), version: 0.1.2
  Using version 0.1.2 (newest of versions: 0.1.0, 0.1.1, 0.1.2)
...
```

Based on the last line, it looks like it's ignoring any versions with letters in them when choosing a default, perhaps thinking that those imply alpha or beta releases. It might be worth putting out a release of 2.0.1, even if there aren't any fixes, just to improve the default installation version.

**Comment by abingham** [comment]
I made the version bump to 2.0.1 and I added python 3.6 to the list of classifiers. After that pip seems to install CR properly into a new 3.6 virtualenv. 

@donkirkby Can you give a try?

**Comment by donkirkby** [comment]
I tested with Python 3.5 and 3.6, and version 2.0.2 now pip installs by default. That should make it easier for users to get started.

**Comment by blueyed** [comment]
Yay, let's close this then.

**Comment by blueyed** [comment]
Just for information: it is nice to see a lot of activity here lately..  keep on going!
