### ISSUE TITLE
celery dependency should be optional

### ISSUE THREAD

**Issue by blueyed** [sixty-north/cosmic-ray#232]
This could be required through `extras_require` in setup.py, so that it gets installed only with `pip install cosmic_ray[celery]`.

This makes the default installation more lightweight, but also helps in case you are using a newer celery in your project already, which might cause:

> pkg_resources.ContextualVersionConflict: (celery 4.1.0 (…), Requirement.parse('celery<4'), {'cosmic-ray'})
> pkg_resources.DistributionNotFound: The 'celery<4' distribution was not found and is required by cosmic-ray

**Comment by abingham** [comment]
This is a good idea. I ultimately want to make celery a dependency of a plugin, not CR itself.

**Comment by blueyed** [comment]
The same applies to `pytest` and `nose`, which should not get pulled in by installing `cosmic_ray`.

**Comment by abingham** [comment]
This is fixed as of cd2edd66fc73ad1ab9156c15d410d19959063fe7. Soon we'll have plugins for pytest and nose as well.

**Comment by blueyed** [comment]
Thank you!
