### ISSUE TITLE
Exceptions in worker with Django (AppRegistryNotReady)

### ISSUE THREAD

**Issue by blueyed** [sixty-north/cosmic-ray#234]
Workers crash when run on a Django project, which uses pytest-django:

```
% cosmic-ray worker proj.app.permissions mutate_comparison_operator 0 pytest -- proj/app/tests/test_utils.py
```

Causes:

```
Traceback (most recent call last):
  File "…/Vcs/cosmic-ray/cosmic_ray/worker.py", line 71, in worker
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "…/project/cosmic-ray/project/app/permissions.py", line 6, in <module>
    from .models import ClientApp
  File "…/project/cosmic-ray/project/app/models.py", line 16, in <module>
    from django.contrib.auth.models import (
  File "…/project/cosmic-ray/.venv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "…/project/cosmic-ray/.venv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "…/project/cosmic-ray/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "…/project/cosmic-ray/.venv/lib/python3.6/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "…/project/cosmic-ray/.venv/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
```

This is after I added the following to `cosmic_ray.worker.worker()` already (at
the top of the `with preserve_modules():` context manager), to cope with
setting up django-configurations (which installs its own import hook):

```python
from configurations import importer
importer.install(check_options=True)
```

But even in case it would work, it seems to be a huge overhead to setup Django
for every mutation?!

**Comment by abingham** [comment]
If I'm reading this correctly, the problem is that django and/or your app require that the modules be imported in a certain order i.e. so that some app registry gets populated at the right time. Is that about right?

This is interesting. We currently mutate the module very early, before the tests are executed. We might be able to restructure things so that the module is mutate "just in time".

**Comment by blueyed** [comment]
That is right.

Django requires apps to be ready before you import (stuff around) them.

**Comment by abingham** [comment]
Ok, hopefully I'll have time to devote to this soon. I'm holding a Cosmic Ray sprint at PyCon UK in a bit, and I think this will be a good topic for someone to look into. Likewise, if you feel like tackling it I'll do my best to give you whatever help I can. I'd love to have more time to put into CR, but I've just got too many other things with deadlines right now :-/

**Comment by abingham** [comment]
I was able to do some work on this during a long flight, and I've [made some progress](https://github.com/sixty-north/cosmic-ray/tree/module-order-dependency). There are probably some lingering issues in the work I've done, but the idea is that we delay the module importation until just before we need to mutate it. If you can, retry that worker invocation you showed using the new branch.

However, there's another issue. During the "init" phase CR will import a module just to figure out any sub-package structure it has. This import also, of course, has to account for the kinds of order dependencies you pointed out. In this case we're not running any code that can set up the context for us (e.g. like a test suite), so we have to import the module directly. It seems like need to let users specify some sort of optional setup or context code to do things like import other requisite modules. Down the rabbit hole...

**Comment by blueyed** [comment]
> we delay the module importation until just before we need to mutate it

Sounds good.
As mentioned in https://github.com/sixty-north/cosmic-ray/issues/233#issuecomment-330369483 it might take a while until I can come back to this.

**Comment by abingham** [comment]
I'm on vacation right now and can't follow through immediately. But IIRC the `module-order-dependency` branch should help alleviate some of this. You could try it out, but I don't know how far behind it is; I should be able to look into this in more detail in a week or two.

Is there some fairly simple way for me to run (some subset of) the django tests under CR to see what's going on and test possible fixes?

**Comment by abingham** [comment]
@fr33ky: I've just pushed up a completely new [`module-order-dependency`](https://github.com/sixty-north/cosmic-ray/tree/module-order-dependency) branch that aims to fix the module import order issue. It's passing our test suite, but I don't think we currently have a reasonable test for module order dependency. Still, it might be work a try if you've got the time.

**Comment by fr33ky** [comment]
@abingham: many thanks! I'll do my best to try this updated branch this week.

**Comment by fr33ky** [comment]
@abingham: it doesn't traceback anymore!

Nevertheless, for the moment, survival rate is 100%… which seems to be weird, from my point of view, as the code coverage is quite importante (>90%).

Code Coverage is >90%
CR: total jobs: 109
survival rate: 100% … mmm…

I'll try to mutate the code manually and check our tests fail or not.

**Comment by abingham** [comment]
Yeah, 100% survival rate generally means something else is wrong, e.g. the tests aren't running properly. One way to sort this kind of thing out is by running workers (i.e. the subprocesses that actually do the mutation and testing) independently. If you run `cosmic-ray dump <session file> | cr-report`, it should show you details of each surviving mutant. Included in these details is a command line of the form `cosmic-ray worker <module name> <operator name> <occurrence>`.

Copy this command line and add the name of your config file to the end of it (e.g. `cosmic-ray my_module core/ZeroIterationLoop 0 my_configuration.conf`), and this will run the worker. The output from this is often enlightening.

As you've suggested, mutating by hand can also be a powerful technique. Try them both.

**Comment by blueyed** [comment]
Thanks for working on this - I hope I can try it soon myself also again.
btw: the comment above sounds like a good section for a debugging / FAQ section.. :)

**Comment by abingham** [comment]
> the comment above sounds like a good section for a debugging / FAQ section.. :)

This is a great idea!

**Comment by fr33ky** [comment]
I selected one mutation (from json created via `init`)
```json
"3": {"diff": null, "filename": "FILENAME", "module": "MODULENAME", "test_outcome": null, "line_number": 202, "worker_outcome": "no-test", "command_line": "cosmic-ray worker MODULENAME core/ReplaceComparisonOperator_Eq_NotEq 2", "data": null, "col_offset": 15, "operator": "core/ReplaceComparisonOperator_Eq_NotEq", "job_id": "0142be2595e7482ba8684ddaea75220f", "occurrence": 2}
```
I mutated the code myself and ran pytest: test failed (which is then fine)

I reverted my modification and ran CR:
```shell
$ cosmic-ray --verbose worker MODULENAME core/ReplaceComparisonOperator_Eq_NotEq 2 CONF.YML
2018-09-10 12:02:32,909 root INFO Reading config from 'CONF.YML'
{"_type": "WorkItem", "values": {"data": null, "operator": null, "worker_outcome": "no-test", "filename": null, "diff": null, "col_offset": null, "test_outcome": null, "module": null, "job_id": null, "command_line": null, "line_number": null, "occurrence": null}}
$ echo $?
0
```

I'm puzzled…

**Comment by abingham** [comment]
Hmm, this is odd. The `no-test` bit is saying that no test was run, so something is happening before the mutation/testing phase. You might try running the worker with the `--keep-stdout` option; by default workers swallow stdout, but this will show it.

Beyond that, it might be simplest if I take a look at things directly. Are you working with the full django test suite?

**Comment by abingham** [comment]
Actually, things looks pretty deeply broken. The worker output shows a totally blank WorkItem: no filename, etc.
