### ISSUE TITLE
Redirect stdout for all test runners?

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#243]
Right now the pytest runner temporarily redirects stdout to devnull. It might be a good idea to do this uniformly for all test runners. By centralizing this feature, we could also *disable* the redirection uniformly; this can be useful for debugging.

**Comment by blueyed** [comment]
Yes, it would be nice to generalize/combine this with the worker's `--keep-stdout`, e.g. by making it a global option maybe?!
Otherwise the worker could pass its flag to the test runner.

**Comment by blueyed** [comment]
Related: https://github.com/sixty-north/cosmic-ray/pull/313
