### ISSUE TITLE
Four human beings -- changed by space-born cosmic rays

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#244]
'born' or 'borne'?

[](https://english.stackexchange.com/questions/10797/what-is-the-difference-between-born-and-borne)

**Comment by abingham** [comment]
It's either a typo in the original comic or an Americanism: http://herocomplex.latimes.com/comics/fantastic-four/

**Comment by rob-smallshire** [comment]
Very good. I believe we should commission a Cosmic Ray logo in the style of a Marvel comic in celebration of 200 GitHub stars!

**Comment by abingham** [comment]
That would be awesome!
