### ISSUE TITLE
Improve new-user documentation

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#246]
I think the biggest problem with the current documentation is that it doesn't orient and on-board new users very well. Get some fresh eyes on this!

**Comment by nedbat** [comment]
Problems I ran into trying to use the quickstart:

1. The new-config command shows creating a .yml file, but the rest of the page talks about a .toml file.
2. new-config asks me questions I don't know the answers to.
3. When I run "exec", I get lots of errors: "cosmic_ray.config.ConfigKeyError: 'cloning'"
4. I copied the "cloning" section from the example into my config.toml, and re-ran exec, same errors.
5. Tried re-running init: now it's doing something. But I can't tell what... maybe a progress bar or spinner of some kind?

I don't mean to gripe, I hope this helps.

**Comment by nedbat** [comment]
It finished, and I had 336 jobs, survival rate: 0.00%, great!

Except when I look at my html report, I have 336 instances of:
```
ImportError while loading conftest '/private/var/folders/j2/gr3cj3jn63s5q8g3bjvw57hm0000gp/T/tmpwo_msnlb/repo/tests/conftest.py'.
py._path.local.LocalPath.ImportMismatchError: ('tests.conftest', '/Users/ned/coverage/trunk/tests/conftest.py', local('/private/var/folders/j2/gr3cj3jn63s5q8g3bjvw57hm0000gp/T/tmpwo_msnlb/repo/tests/conftest.py'))
```
which I guess means this is more complicated to get going than I thought. :(

Also, BTW: why "cr-report" and "cr-html" instead of "cosmic-ray report" and "cosmic-ray html"?

**Comment by abingham** [comment]
> I don't mean to gripe, I hope this helps.
Thanks! All of this kind of input is absolutely helpful. I just hope I have some time in the near future to sit down and give this documentation some polish.

**Comment by abingham** [comment]
> which I guess means this is more complicated to get going than I thought. :(

Interesting. Is this for a project I can get access to? I can try to replicate what you're seeing.

> Also, BTW: why "cr-report" and "cr-html" instead of "cosmic-ray report" and "cosmic-ray html"?

My hope is to separate the reporting tools from the core of CR. These tools could become arbitrarily complex in themselves, and there's no good reason (except convenience, perhaps) to tie their development to CR too tightly. It may be that I've made the wrong decision here, but I hope that keeping them separate engenders other independent tools.

**Comment by abingham** [comment]
@nedbat I've moved this discussion of coverage over to #426
