### ISSUE TITLE
Separate generating work items from insertion into database

### ISSUE THREAD

**Issue by nebulans** [sixty-north/cosmic-ray#255]
Currently, work item generation in the `init` command is tightly coupled to their insertion into the work database.  Decoupling the two would allow workflows which never write the session to disk, eg driving by py.test, or allow more plugable database backends.

**Comment by abingham** [comment]
It shouldn't be too hard to create a new command which just produces the work list, maybe something like `cosmic-ray work-items <config>`. Or if a config feels too heavyweight for this, we could just pass in the necessary arguments on the command line.

If this command wrote a sequence of `WorkRecord`s to stdout (i.e. like `dump`) would this be sufficient?
