### ISSUE TITLE
asyncio?

### ISSUE THREAD

**Issue by gaborbernat** [sixty-north/cosmic-ray#257]
There's a lot of I/O handling here, considering the nature of the mutation test. Seems to me like perfect candidate for asyncio.

**Comment by abingham** [comment]
Do you have concrete suggestions of where to use it? There are some places where we technically *could* use asyncio, but I don't see any practical benefit to doing so. I'm not generally inclined to use asyncio (or any technology) for the sake of the technology itself.

**Comment by blueyed** [comment]
I guess most the time is spent with the test runner(s) anyway, isn't it?

**Comment by rob-smallshire** [comment]
Mutation testing is heavily CPU bound, not I/O bound. On top of that async code is significantly more awkward to work with than sequential Python code, and it's also inherently viral up and down the call stack.

**Comment by abingham** [comment]
@blueyed You're correct. Except in rare (and not practically useful situations) almost all time should be spent executing tests in workers/runners. Some of the execution engines might benefit from asyncio, but I don't think that needs to influence the rest of the implementation.
