### ISSUE TITLE
Quickstart invocations are out of date

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#267]
The Quickstart document at http://cosmic-ray.readthedocs.io/en/latest/quickstart.html instructs me to issue the command:

    cosmic-ray init config.yml my_session

This fails with:

    $ cosmic-ray init config.yml my_session
    usage: cosmic-ray init [options] [--exclude-modules=P ...] (--timeout=T | --baseline=M) <session-name> <top-module> [-- <test-args> ...]

**Comment by rob-smallshire** [comment]
This also applies to the example of running the Adam tests at http://cosmic-ray.readthedocs.io/en/latest/quickstart.html#a-concrete-example-running-the-adam-unittests

**Comment by rob-smallshire** [comment]
I'm using latest cosmic-ray available from PyPI:

$ cosmic-ray --version
cosmic-ray v.2

**Comment by abingham** [comment]
Ah yes, sorry about that. There have been some really significant changes since since the PyConUK sprint, and I've neglected to push up a new PyPI version. I'll do that soon.

**Comment by abingham** [comment]
I've pushed up version 3.0.1a0, so the instructions should apply to pip installs now (though I'll admit that getting pip to install the latest version can be a challenge). I'll go ahead and close this, but reopen it if things still don't work.
