### ISSUE TITLE
config.yml is too generic a name

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#269]
My project already has a `config.yml` for its own purposes.  This is a very generic name. Consider having Cosmic Ray use a more specific name for its own configuration file, such as `cosmic-ray-config.yml`

**Comment by abingham** [comment]
You can call the config file whatever you want; we don't look for a specific file name. But we should probably update the docs to make this more clear.

**Comment by abingham** [comment]
This should be fixed as of 8719578ad059a527798e133f6cc82b1e4b85a05c. Re-open this if it's still not clear.
