### ISSUE TITLE
Use appropriate return codes

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#270]
I'm a stickler for using appropriate return codes where possible. This is even more important in these days of highly automated built-test-deployment pipelines. It's much easier to test a return code than it is to screen-scrape the whatever the program is babbling about on stdout or stderr.

For example, when Cosmic Ray is invoked incorrectly, it currently returns 1. Ideally it would return 64 which is the standard Unix return code for incorrect usage.

The requisite return codes are available in the `os` module, for example `os.EX_USAGE`.

**Comment by abingham** [comment]
This is a good idea.

**Comment by abingham** [comment]
I think I've addressed this on the [`proper-usage-exit-code` branch](https://github.com/sixty-north/cosmic-ray/tree/proper-usage-exit-code). 

Interestingly, this is probably most appropriately addressed in docopt where the `SystemExit` subclass is raised on incorrect usage; they should probably be setting the exit code to `os.EX_USAGE`. As it is, we catch their exception, set the error code, and re-raise it.
