### ISSUE TITLE
Deploy to pypi via travis

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#272]
We should investigate deploying new versions to pypi when travis passes:

https://docs.travis-ci.com/user/deployment/pypi/

Perhaps when a build passes on master we can push to pypi. Or perhaps when a new tag is created. Whatever policy we use, we'll need to bump the version string somehow.

**Comment by rob-smallshire** [comment]
We should look at what MacIver is doing with Hypothesis for deployment. They have automated deployment like this coupled with semantic versioning.

**Comment by abingham** [comment]
The hypothesis deployment system is something like this:

1. To create a new release, you add a `RELEASE.rst` to the repo. This specifies a release type (major, minor, patch) and a list of changes.
2. Travis looks for this file. If it's found, travis updates `changes.rst` with the changes, updates `version.py`, deletes `RELEASE.rst`, and commits this all to git.
3. It waits for travis to finish its jobs (tests, I assume)
4. It builds the necessary pypi distributions and pushes them up.

Since travis needs access to pypi passwords and such, there's also some work to decrypt a "secretes" file.

This could work for us, and it has some nice properties (e.g. the RELEASE.rst is the single source of truth for new version numbers), but it feels a bit heavyweight. If we're willing to take on the responsibility of keeping `version.py` and `changes.rst` (which we don't even have right now) in sync, it might be simpler to just make pypi releases when we push a new tag. This avoids the little dance of creating a RELEASE.rst and then pulling after its deletion.

**Comment by abingham** [comment]
This works as of 107371a2c65083a8cb70e11ce5c8c61737f8caa1. Very cool!

**Comment by abingham** [comment]
The strategy right now is that we a) bump the version in `cosmic_ray/version.py` and b) push to the release branch. When travis sees this push it does a pypi deployment and git release tag.
