### ISSUE TITLE
Better instruction required for "test args"

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#277]
When using cosmic ray for the first time, it wasn't clear to me from the description what "test args" was, and that it would typically contain at least the name of the test directory. See #275.

**Comment by abingham** [comment]
Ultimately this is going to require test-runner-plugin specific information. I'd like the config system to be self-documenting on some level, and this means that plugins will need to somehow provide documentation about what they expect in their "args" field. We might also be able use some schema-based system where configuration can be validated before use.
