### ISSUE TITLE
Usage information not reported for incorrect invocations

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#286]
Incorrect invocations don't display any usage information:

    $ cosmic-ray
    $

Although I do get the new EX_USAGE exit code.

**Comment by abingham** [comment]
This is pretty ugly. When docopt detects a parse error, it raises a `DocoptExit` exception, which is a subclass of `SystemExit`. This has `code` attribute which can be a) an integer, in which case this is the exit code or b) another object in which case `None` results in errcode 0 and anything else is printed and results in errcode 1. Critically, there is no way to set `code` to an error string *and* provide an errcode other than 1. 

Docopt is setting `code` to it's error string, and this is why we were originally seeing errcode 1. When I caught the DocoptExit exception and set it's `code` to `os.EX_USAGE`, I unwittingly obliterated the error string.

What I'm going to try is to a) catch `DocoptExit` as we currently do, b) print its `code`, c) change it's `code` to `os.EX_USAGE`, and d) re-raise it. I think will give us the full effect we're looking for, i.e. printing the usage message as well as giving the correct error code.

**Comment by rob-smallshire** [comment]
Can't we just print the message ourselves (by converting the DocoptExit object to a string?) and then sys.exit(os.EX_USAGE) ?

Maybe it's my inner C++ programmer but I don't really like the idea of exceptions escaping from main(). I'd rather have main() _return_ an exit code and then have `sys.exit(main())` in the `__main__` _block_.

**Comment by abingham** [comment]
That would probably work as well. I guess I was keeping the original semantics (i.e. exiting via SystemExit) as much as possibly.

**Comment by abingham** [comment]
Fixed in [PR 290](https://github.com/sixty-north/cosmic-ray/pull/290), 30b5eb3b947198d691896606cfd46aebc2e5eca0

**Comment by abingham** [comment]
> then have sys.exit(main()) in the __main__ block.

Actually this won't work directly since the `cosmic-ray` command is actually a console-script entry point...the __main__ block won't execute. But calling `sys.exit()` from `main()` would work just fine, I think.

**Comment by rob-smallshire** [comment]
Good point. Good to know that command-line interfaces are still the hardest thing in 2017.

**Comment by rob-smallshire** [comment]
Apparently, the console-script entry point is expecting to receive the exit code as the return value, so it will work. https://packaging.python.org/specifications/entry-points/#use-for-scripts

**Comment by abingham** [comment]
I've updated the CLI to return error codes from main and sys.exit() from __main__ in [PR 297](https://github.com/sixty-north/cosmic-ray/pull/297).
