### ISSUE TITLE
Odd cli.py docstring formatting

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#287]
I've submitted a [pull-request to docopt-subcommand](https://github.com/abingham/docopt-subcommands/pull/15) which should allow the strangely dedented docstrings in the `cli.py` command handlers to be indented normally.

**Comment by abingham** [comment]
I've merged in the docopt-subcommands PR and pushed a new version to PyPI. If this fixes things for you, go ahead and close this. Thanks!

**Comment by rob-smallshire** [comment]
In conjunction with #289 it would be fixed.
