### ISSUE TITLE
Respond to SIGINFO to report progress

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#295]
On macOS and BSD systems you can send SIGINFO to the foreground process by pressing Ctrl-T. This usually results in a short progress report being printed to the console.  This could be a good way of honouring the "silence is golden" UNIX principle, while also being able to get some useful progress feedback if you've forgotten to run with `--verbose`.

Although Linux doesn't support SIGINFO, it's apparently customary to use SIGUSR1 for the equivalent purpose.

**Comment by abingham** [comment]
It's an interesting idea! The work database is transactional, so it should be easy (famous last words) to extract the progress data in a signal handler. 

As a stop-gap, currently you can run `dump` commands against an active `exec` run and get up-to-date results.

**Comment by rob-smallshire** [comment]
According to the TinyDB page it shouldn't be used from multiple processes:

> Why Not Use TinyDB?
> You need advanced features like:
> access from multiple processes or threads

Although running dump (or some other more refined progress-reporting command) would usually work, it sounds like it wouldn't be guaranteed to work.

**Comment by abingham** [comment]
Ah! Good to know. My expectations of tinydb have grown beyond reality.

In any event I think tinydb is not likely to scale well. This is just my
gut assessment, but when we start to get billions of mutations I worry
about it's ability to keep up.

**Comment by drorasaf** [comment]
IMHO, I think that for small scale project tinydb would still be relevant but it might be good to consider a bigger type of database options considering that big software projects might has many mutations, as well as combined with continuous integration, might pose this change

**Comment by abingham** [comment]
I started with tinydb because it was extremely easy to use, and it was easy to inspect. For initial development purposes it was excellent, but I don't want to keep it around once it's past its usefulness.

At the same time, I also don't want to force users to use anything too heavyweight. So we might look at replacing tinydb with sqlite. My experience with sqlite is that it's fast and robust, though I don't know how it handles huge numbers of rows.

**Comment by rob-smallshire** [comment]
People are reporting success with SQLite databases with millions of rows per table. Mutation testing on a code base large enough to produce that many mutations, which will likely be hundreds of thousands of lines of Python, will likely hit other performance limits inherent in mutation testing long before database performance becomes a problem.

I think SQLite is an good choice for the next step.

**Comment by drorasaf** [comment]
what about codernityDB? similar to tinydb but more efficient and provide multi-threading/processing capablities

**Comment by abingham** [comment]
That's an interesting one I hadn't seen before.

**Comment by abingham** [comment]
An upcoming change is going to move over to sqlite.
