### ISSUE TITLE
Orderly shutdown on SIGINT

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#303]
If you interrupt cosmic-ray with SIGINT (Ctrl-C) you might see this:

```
rjs@Blaven:~/dev/asm68 (asm68) (master *)
$ cosmic-ray exec cosmic-ray-session3
^C
rjs@Blaven:~/dev/asm68 (asm68) (master *) [130]  <--- exit code
$ 
... wait for quite a while ... then suddenly

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

I don't think it's required that SIGINT exits immediately, and goodness knows what state we're leaving the database in, so it's probably better to inform the user than we've got the message, and that we're winding things down in an orderly way.  This could just be a case of setting a flag somewhere which we periodically check.

**Comment by abingham** [comment]
I think this is much less of a problem now, so I'm going to close this.
