### ISSUE TITLE
Logging integration with reporting system

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#305]
It might be good/useful to have a logging-based way to interact with the new reporting system. See the discussion in [this PR](https://github.com/sixty-north/cosmic-ray/pull/304) for the initial thoughts in this direction.

**Comment by abingham** [comment]
This has some not-so-simple edges to sort out. At a high level, it seems that the appropriate way to approach this is to have a `LogHandler` subclass that records PROGRESS-level messages so that the most recent can be reported on demand. But what if the user installs two of these handlers...do they each report the same progress? Or do we try to ensure that a single progress message is only ever reported once? There are ways to make this happen (e.g. with singletons) but that feels overly complex. 

Also, what's the relationship between the handler being installed and the reporting? If we uninstall the handler, should that mean that progress previously reported through that handler should not be reported in progress requests? This might be difficult because we don't get any signal that a handler has been removed. `LogHandler.close()` seems to be called at shutdown or something, *not* when a handler is removed...there's not `LogHandler.removed()` method that I can find.

Maybe I'm just too tired right now to think correctly about this.

**Comment by rob-smallshire** [comment]
I wonder if, in spite of it's superficial attractiveness, this idea is mixing concerns. Should progress reporting be conflated up with diagnostics?

**Comment by abingham** [comment]
I don't think we're mixing concerns too much, but this idea is probably not as convenient or useful as I'd imagined. I pushed up some changes to the [progress-logging branch](https://github.com/sixty-north/cosmic-ray/tree/progress-logging) that implement the idea, but it's probably more trouble than it's worth, at least for now. If you progress-reporting needs were more substantial we'd probably have a better idea of what to do.
