### ISSUE TITLE
Deploy and run tests on cloud infrastructure

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#306]
I'm discovering that mutation testing can be very resource intensive, even on small projects. It would be nice if Cosmic Ray exposed some hooks so that cloud infrastructure could be provisioned and decommissioned automatically as part of a `cosmic-ray exec` run.

I imagine this could involve invoking Terraform and Ansible to provision and configure remote workers, although we probably don't want to couple Cosmic Ray to specific tools.

**Comment by abingham** [comment]
My vision for this is that you would create a new execution engine. This is
not completely thought-out, but that's been the "plan" for a while.

**Comment by drorasaf** [comment]
what about to create an example with either gcloud or aws, or maybe use packer as a multi cloud compatible json environment for this?

**Comment by abingham** [comment]
> what about to create an example with either gcloud or aws

That's the obvious next step. It's just a question of time and resources. If I do this it'll probably be on AWS since I have more experience with it, but I think any of the popular cloud platforms would prove the point.

**Comment by drorasaf** [comment]
some assumptions:
1. As is the setup with Celery, it is external dependency and I think it should stay that way
2. The execution engine should be responsible for delivery and distribution of the tasks. AWS SQS/ GCP PUBSUB.

Proposal for interface with cloud:
`cr-cloud op configFile` 
`cr-cloud setup cloud.yaml`
Setup is responsible for initializing all resources
`cr-cloud teardown cloud.yaml`
Teardown is responsible for shutdown all resources
`cr-cloud run cloud.yaml session`
Run would be syntactic sugar for:
1. cr-cloud setup cloud.yaml 
2. cosmic-ray init session.config session
3. cosmic-ray exec session
4. cr-cloud teardown cloud.yaml

The configuration file options:
1. cloud provider
2. region
3. amount of workers
4. Max time for workers to exist
Currently I think that using the smallest machine and using a single worker is the best approach, we could be able to test it in the future.

**Comment by abingham** [comment]
Your assumptions are correct. CR itself won't depend on any cloud-related packages, etc. The execution engine plugins themselves might (and probably should) have such dependencies, though.

I'm not in favor of adding a new tool (i.e. `cr-cloud`) to CR itself. I want to keep CR focused on it's core job, and managing cloud infrastructure is a separate, complex, and fast-moving domain. I think we're best off leaving cloud management to tools like terraform, et al. However, if someone wants to develop a separate package to implement `cr-cloud`, that's fine.

Really, though, we're thinking much along the same lines. If you replace (1) with `terraform apply` and (4) with `terraform destroy`, then that's basically what I have in mind. CR won't care *how* you provision your cloud infrastructure, it'll just pass configuration information to the plugin.

**Comment by drorasaf** [comment]
I thought mainly on cr-cloud just to provide a syntactic sugar for the run operation since most of the time, people just want to run it out of the box.

**Comment by abingham** [comment]
I think you'd do best to develop `cr-cloud` as a separate project. I may be entirely wrong about its utility, but for my own sanity I want to keep it separate from CR, at least for now. I don't see much benefit to putting it into CR, and actually I see a lot of benefit to keeping it out. In particular, it'll be easier to develop something like `cr-cloud` if you don't need to keep doing PRs against CR; it can develop at its own rate.
