### ISSUE TITLE
PyPI requires reStructuredText

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#309]
Currently we're pushing Markdown to PyPI so the project landing page there looks messy. 

https://pypi.python.org/pypi/cosmic_ray/1.0.0a0

The easiest thing to do is probably to create a very simple reStructuredText page for PyPI which directs readers towards to GitHub.

**Comment by abingham** [comment]
The [most recent version](https://pypi.python.org/pypi/cosmic_ray) is using RST.
