### ISSUE TITLE
How can I configure execution engine

### ISSUE THREAD

**Issue by drorasaf** [sixty-north/cosmic-ray#350]
I take celery3 execution plugin as an example, and I am aware that celery has many options to configure, but I haven't found a way to configure it through cosmic ray. any insights?

side note: version of celery3 should probably be 0.0.1 and not 0.0.0

**Comment by abingham** [comment]
The basic strategy for configuring execution engines is that we pass the
entire "args" structure in the confit to the plugin. That is, in the config
we have:

test-runner:
name: pytest
args: <some yaml structure>

We pass the entire structure after "args" to the engine plugin. It's up to
the plugin to decide what to do with the data, and it's up to the engine to
document what it accepts in the config.

So the answer right now is that the engine probably doesn't support the
configuration options you're interested in. We'd need to add them to the
engine's configuration handling code somewhere.

**Comment by drorasaf** [comment]
Excellent thanks.
might need to rethink how to make it forward compatible once new configurations are introduced,

**Comment by boxed** [comment]
@drorasaf Sorry to spam here but couldn't find your contact info. You could give my mutation tester mutmut (https://github.com/boxed/mutmut/) a try. It's a much simpler system and easier to work with I think. I'd love some feedback on how you see the differences between CR and mutmut (and I think the CR developers would too!)
