### ISSUE TITLE
Cosmic-ray==3.1.0 init doesn't work

### ISSUE THREAD

**Issue by donato** [sixty-north/cosmic-ray#352]
Using python 3.6 and cosmic-ray 3.1.0, the init doesn't do anything. Verbose is also silent
```
cosmic-ray init config.yml my_session                                                                                                                                                     
```

Uninstalling and using cosmic-ray v3.0.6 immediately works

**Comment by abingham** [comment]
Hmmm...there was a pretty big change in there, and it's possible we broke something.

Are you installing it from source, via `pip`, or what? 

What's in `config.yml`?

When you say nothing happens, do you mean that `my_session.json` is not created?

**Comment by donato** [comment]
1. Installation method: pip
2. config.yml: doesn't exist, and no text outputs
3. my_session is not created either

**Comment by abingham** [comment]
The main issue is that CR isn't giving very good feedback. When a config doesn't exist, init silently fails (technically it sets the error code, but that's not visible).

I've created [the `improved-load-config-feedback` branch](https://github.com/sixty-north/cosmic-ray/tree/improved-load-config-feedback) that should improve the situation. Can you try it out and let me know if it fixes things for you?

**Comment by donato** [comment]
Manually creating the config file does allow it to successfully create a
session.json.

Maybe this can be fixed with a simple tweak to the docs? They describe a
q/a which builds out the config file.

Thanks for your response, happy holidays!

**Comment by abingham** [comment]
Ah, you're right! Sorry about that. I'll update the docs as well.

**Comment by abingham** [comment]
@donato I've create [a branch](https://github.com/sixty-north/cosmic-ray/tree/improved-new-config-docs) with some documentation improvements. Can you have a look at it and let me know if it seems both correct and sufficient to you? It's good for us to get fresh eyes like yours on the docs.

Thanks for working with us on this, and God Jul from Norway!
