### ISSUE TITLE
report: group mutants by location

### ISSUE THREAD

**Issue by snarfed** [sixty-north/cosmic-ray#366]
i'm happily going through my dump, looking through the survived mutants, and thinking about the new tests i need. exciting. thanks for making this tool!

one thought: many of my mutants turn out to be the same root location in my code, just replaced with different operators. binary operators in particular: one location has 11 separate `ReplaceBinaryOperator_*` mutants reported, differing only by the new operator. there are also other smaller groups with `ReplaceComparisonOperator_*`, `NumberReplacer`, etc.

the new test(s) or bug fixes for these groups will often be the same, regardless of the specific mutants in the group, or how many there are. you might want to consider grouping them in the `cosmic-ray dump` output somehow. maybe even just show the diff for the first, and then list the other operator replacements that also failed, with a command line flag to optionally show them all.

also, oddly, i have a handful of actually identical duplicate `ReplaceAndWithOr` and `ReplaceAndWithOr` mutants in a few places. happy to file a different issue for those if you want, just let me know. example:

```
job ID eb73563d0ebc40eca26a7ad0f11ed268:survived:granary.microformats2
command: cosmic-ray worker granary.microformats2 core/ReplaceAndWithOr 25
--- mutation diff ---
--- a/Users/ryan/src/granary/granary/microformats2.py
+++ b/Users/ryan/src/granary/granary/microformats2.py
@@ -269,7 +269,7 @@
     start = props.get('start', [])
     end = props.get('end', [])
     event_times += [('  <time class="dt-start">%s</time>' % time) for time in start]
-    if (start and end):
+    if (start or end):
         event_times.append('  to')
     event_times += [('  <time class="dt-end">%s</time>' % time) for time in end]
     return HENTRY.substitute(prop, published=maybe_datetime(prop.get('published'), 'dt-published'), updated=maybe_datetime(prop.get('updated'), 'dt-updated'), types=' '.join((parent_props + types)), author=hcard_to_html(author, ['p-author']), location=hcard_to_html(location, ['p-location']), categories='\n'.join((people + tags)), attachments='\n'.join(attachments), in_reply_tos=in_reply_tos, invitees='\n'.join([hcard_to_html(i, ['p-invitee']) for i in props.get('invitee', [])]), content=content_html, content_classes=' '.join(content_classes), comments=comments_html, children='\n'.join(children), linked_name=maybe_linked_name(props), summary=summary, event_times='\n'.join(event_times))

job ID 6fde419f4bdb4c38a2433e5e2234ed46:survived:granary.microformats2
command: cosmic-ray worker granary.microformats2 core/ReplaceAndWithOr 26
--- mutation diff ---
--- a/Users/ryan/src/granary/granary/microformats2.py
+++ b/Users/ryan/src/granary/granary/microformats2.py
@@ -269,7 +269,7 @@
     start = props.get('start', [])
     end = props.get('end', [])
     event_times += [('  <time class="dt-start">%s</time>' % time) for time in start]
-    if (start and end):
+    if (start or end):
         event_times.append('  to')
     event_times += [('  <time class="dt-end">%s</time>' % time) for time in end]
     return HENTRY.substitute(prop, published=maybe_datetime(prop.get('published'), 'dt-published'), updated=maybe_datetime(prop.get('updated'), 'dt-updated'), types=' '.join((parent_props + types)), author=hcard_to_html(author, ['p-author']), location=hcard_to_html(location, ['p-location']), categories='\n'.join((people + tags)), attachments='\n'.join(attachments), in_reply_tos=in_reply_tos, invitees='\n'.join([hcard_to_html(i, ['p-invitee']) for i in props.get('invitee', [])]), content=content_html, content_classes=' '.join(content_classes), comments=comments_html, children='\n'.join(children), linked_name=maybe_linked_name(props), summary=summary, event_times='\n'.join(event_times))
```

**Comment by abingham** [comment]
> also, oddly, i have a handful of actually identical duplicate ReplaceAndWithOr and ReplaceAndWithOr mutants in a few places. happy to file a different issue for those if you want, just let me know.

Yes please, a separate issue would be best. I have some idea what's going on there, but it would require some investigation.

**Comment by abingham** [comment]
The grouping you're describing is probably a good idea. We've given some thought to a reduced set of operators - those deemed to be most "effective" - to deal with essentially the same problem, but we haven't done anything yet.

But simply formatting the output should be relatively straightforward. We wouldn't want to modify the `dump` output, but rather modify the `cr-report` tool (or perhaps create a new tool). The separation between `dump` and user-facing report tools exists precisely to support this kind of stuff. 

I can imagine a flag to `cr-report` that does this, perhaps
```
cosmic-ray dump session.json | cr-report --group-by-location
```
I probably won't have any time to put into this in the near future, but I'll be happy to help you pull it together if you want.

**Comment by snarfed** [comment]
> We wouldn't want to modify the dump output, but rather modify the cr-report tool (or perhaps create a new tool).

ah, true! sorry, i misspoke, this is in the cr-report output.

> I probably won't have any time to put into this in the near future, but I'll be happy to help you pull it together if you want.

thanks! understood. unlikely for me too, but i'll definitely keep it in mind.

thanks again for cosmic-ray!
