### ISSUE TITLE
Asking for help on a non-existent command gives mangled message

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#368]
Note the first line after the command shows format string replacement fields:

```
$ cosmic-ray help foo
"{}}" is not a valid command foo
cosmic-ray

Usage: cosmic-ray [options] <command> [<args> ...]

Options:
  -h --help     Show this screen.
  -v --verbose  Use verbose logging

Available commands:
  baseline
  config
  counts
  dump
  exec
  execution-engines
  help
  init
  interceptors
  new-config
  operators
  test-runners
  worker

See 'cosmic-ray help <command>' for help on specific commands.
```

**Comment by abingham** [comment]
I think this is really a bug in `docopt-subcommands`. I'm pretty sure I've seen in other programs. 

It's probably related to [issue 11 on `docopt-subcommands](https://github.com/abingham/docopt-subcommands/issues/11).

**Comment by abingham** [comment]
This should be fixed as of [this commit in `docopt-subcommands`](https://github.com/abingham/docopt-subcommands/commit/340380108d82792d4d115fe9582b60deeda71cc6).
