### ISSUE TITLE
Command not accepting session filename hinders usability

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#370]
Having to type:

    cosmic-ray exec local-session-1

is more difficult than having to type:

    cosmic-ray exec local-session-1.json

because I can't use tab-completion.

Some possible solutions:

* Accept the filename instead of, or as well as, the session base name.

* Provide bash, zsh, etc. completion support for Cosmic Ray.

**Comment by abingham** [comment]
Does it not work if you add ".json"? It should, and it seems to work for me. `cosmic_ray.config.get_db_name` does precisely what you describe: if the database name you provide on the command line does not end in ".json" it appends it. 

With that said, I've never been entirely happy with that. That patch came from a sprint, I think, and it feels a bit too cute for my taste. I'm tempted to only accept filenames and change the extension as described in #372.

**Comment by rob-smallshire** [comment]
You're right, it works. I think it was just learned behaviour on my part this it didn't work.
