### ISSUE TITLE
Terminating cosmic-ray exec does not cancel jobs

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#371]
When using the celery3 worker plugin, cancelling cosmic-ray exec with SIGINT leaves all the workers running. Obviously this can consume a lot of resources. Presumably the results just hang around in the message broker, and are lost unless the queue is persistent, so the work probably goes to waste.

Suggestion: Terminating cosmic-ray exec should cancel any pending jobs.

Workaround: Terminate the celery worker process.

**Comment by abingham** [comment]
Do you mean the processes spawned by the `cosmic-ray exec` call in `cosmic_ray.worker.worker_process`? I would have expected those to die "organically".

> Suggestion: Terminating cosmic-ray exec should cancel any pending jobs.

The celery3 engine already makes an attempt to purge the job queue in a `finally` block, but perhaps SIGINT bypasses that. Definitely the *intent* is to behave as you describe.

**Comment by rob-smallshire** [comment]
Yes, they keep running.

**Comment by abingham** [comment]
Hmm. This is very strange then. I would expect the actual celery worker processes to live; they are independent of the cosmic-ray run. But if the subprocesses they spawn are living after the exec work is done, then there's something going on that I don't yet understand. I'll try to replicate this.
