### ISSUE TITLE
init does not ask questions or generate config file if config file is missing

### ISSUE THREAD

**Issue by jimrybarski** [sixty-north/cosmic-ray#383]
I entered this command in a fresh repo with one function and one test: `cosmic-ray init config.yml my_session`

The output is below, which had a return code of 78:

```Error loading configuration from config.yml
[Errno 2] No such file or directory: 'config.yml'
```

The documentation claims this should ask me a series of questions and create config.yml. I was able to manually create the config file and run CR successfully, so it was not an issue with the organization of the repo.

Versions: 
cosmic-ray==3.1.2
pytest==3.6.3
cosmic-ray-pytest-runner==0.0.0
Python 3.6.5

**Comment by abingham** [comment]
Hmm, it looks like the only docs aren't building properly so what you're seeing is outdated. The command you're looking for is `cosmic-ray new-config <config file name>`. I'll look into the docs.

**Comment by abingham** [comment]
I've updated the online docs. I'm going to close this issue since I think it's fixed, but please reopen it if I haven't solved your problem. Thanks for reporting it!
