### ISSUE TITLE
Django cosmic-ray integration

### ISSUE THREAD

**Issue by stashkov** [sixty-north/cosmic-ray#387]
Hi there,

Is there a documentation on how to mutation test existing Django `unittest.TestCase` suite? I'm having trouble making it work.

**Comment by abingham** [comment]
If it's a test suite based in unittest, it should just work...in principle.
I'm sure there are edge cases we don't handle well, and it would not
surprise me if django finds them.

What issues are you seeing?

Also, I'm on vacatio right now and my support will be spotty at best for
the next few weeks.

**Comment by stashkov** [comment]
Hope you had a lot of fun during your vacation (or even better you're still on vacation)! 

I figured out a temporary solution. Maybe I will come back later with a suggestion for a proper solution for this :) 

Thank you for your work!

**Comment by abingham** [comment]
You might try the [`module-order-dependency`](https://github.com/sixty-north/cosmic-ray/tree/module-order-dependency) branch. The current `master` branch will generally import modules in a different order than the actual test suite, and this problematic for some projects like django. This new branch attempts to preserve module loading order while still doing the mutation. It *seems* to work.
