### ISSUE TITLE
Remove backported "redirect_stdout"

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#390]
We backported 3.4's `redirect_stdout`, but now we don't support anything earlier than 3.4. So we can remove this backport (but not the `redirect_stderr` one...erg).

**Comment by objarni** [comment]
Why can't redirect_stderr backport be removed?

**Comment by abingham** [comment]
[Accd to the docs](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stderr), it wasn't introduced until 3.5.

**Comment by abingham** [comment]
Although...if your point is that we apparently don't actually *use* `redirect_stderr` anymore, then it's a good one! Perhaps we should just remove it entirely.

**Comment by objarni** [comment]
You seem to be using redirect_stderr at some places. Sorry.

![image](https://user-images.githubusercontent.com/68198/45357425-78d24b80-b5c6-11e8-8347-80a9179f03b8.png)

**Comment by abingham** [comment]
Ah, right, down in the nose runners (the ones in `util.py` are our implementation). We should at least review whether those are necessary. I could even be convinced that we don't need the nose runners any more, or that that they could be moved into a separate repository.

**Comment by objarni** [comment]
Why did you need the nose runners once upon a time..?

**Comment by abingham** [comment]
It was a framework I was using for something. So when I started CR is seemed like a reasonable extension to have. Nose was more popular back then, but I think it's pretty dead now.

**Comment by objarni** [comment]
OK. If you began CR development today, what would you do?

BTW I like the fact that you do not support Python2.7 ... It is about time tools and libraries started favoring 3.x series primarily instead of 2.7 primarily.

I guess for this particular project, which is really usable i legacy code, it is a little bit at odds with "economics" though :)

**Comment by abingham** [comment]
> OK. If you began CR development today, what would you do?

I'd probably ignore nose altogether. What I'm not sure about is if anyone's using that plugin.

> I guess for this particular project, which is really usable in legacy code*, it is a little bit at odds with "economics" though :)

Our view is that CR won't be ready for a lot of real-world projects for a while, and hopefully the world will have caught up by then. Honestly, the overriding economics so far has been whether we can use it ourselves.

In thinking about support for 2.7 in the past, I came to the conclusion that it would need to be effectively another project. A big problem is that the abstract syntax tree has changed between 2 and 3, so CR operators would not always know how to handle a Python 2 AST. I suppose an interesting question is how much infrastructural code the two versions could share; in principle it's quite a bit, but I've not been shy about using Python 3-only stuff in the codebase.

**Comment by objarni** [comment]
I understand! And as the project is in the "startup" phase, supporting only 3.4+ makes a lot of sense. 2.7 is at end-of-bugfix-lifetime in less than 1.5 years after all!

Did you catch the last question, somewhat hidden under an asterix note? This:

Is it possible to tell CR to use Py2.7 toolchain/env for the target "subject"? If yes, then the tool CR could support 3.4+, but still be usable in legacy industry systems...

And know that I know a little more on what CR is doing - mutating the AST and all - I can answer the question myself: No, it is not possible.
