### ISSUE TITLE
More robust retrieval of worker output

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#391]
Right now, we get results from worker subprocesses by parsing their stdout. While this is nice and simple, it's not robust against certain behaviors. In particular, if a test launches a subprocess which itself write to stdout, this shows up in the worker's stdout (from the launching process's point of view) and breaks things.

This came up initially in #386 where approval was launching a diff command which printed to stdout.

We need to find a more robust way of getting results from workers, one that doesn't place any constraints on tests (i.e. allows them to write to stdout if they want) but which reliably gets results to the exec process.

**Comment by objarni** [comment]
`I'd still want workers to write to stdout but default...this is a very useful debugging technique. `

If it is a useful debugging technique, but works against 'production', maybe favor production and make the debugging technique available via a flag, config file or other such 'developer' methods?

**Comment by abingham** [comment]
> maybe favor production and make the debugging technique available via a flag

My instinct is that I'd rather keep it simpler for humans, i.e. during debugging. Computers aren't bothered by having to type extra flags, etc. Ultimately you may be right, but that's my sense for now.

**Comment by abingham** [comment]
> Why not always write to both

Because there won't always be a socket to write to.

**Comment by abingham** [comment]
I've pushed a change which uses `multiprocessing` to run the worker subprocess. Results are now passed back through a `Pipe` rather than stdout, so we sidestep the entire issue of worker subprocesses and their stdout.

I'm going to close this for now since the problem seems to be fixed.
