### ISSUE TITLE
Filter equivalent mutants

### ISSUE THREAD

**Issue by dementati** [sixty-north/cosmic-ray#397]
Hi, not sure if this is the appropriate place for this, but I'm curious if there is any way to label particular mutants as equivalent and ignore them in the report. I want to be able to get my survival rate down to 0% and if there are remaining equivalent mutants I cannot, even though they are not indicative of a weakness in my test coverage.

**Comment by abingham** [comment]
There *is* a supported way to do what you want, but it's pretty bleeding-edge. In short, we have a tool called [`spor`](https://github.com/abingham/spor) that let's you attach arbitrary metadata with ranges of code. `spor` is entirely independent of CR, and is under active development. 

For it's part, CR is able to use `spor` to look for metadata telling it not to mutate certain ranges of code. CR does this via its "interceptor" mechanism, which was built to support the use of tools like `spor`.

So, to tell CR not to do things that result in equivalent mutants, you can mark the range of code that it shouldn't mutate. In principle, CR will see that metadata and simply not do anything on those parts of your code. We actually even have tests for this; if you look in `test/test_project/.spor` - the body of code we use for our integration tests - you'll see the metadata anchor files.

I would be delighted to help you use this feature, but beware that the whole thing is held together with spit and bubblegum right now. I expect that there will be a quite a bit of churn around anchored metadata, both from the `spor` end of things as well as the CR end. But if you're feeling adventurous, it should work...
