### ISSUE TITLE
new-config command doesn't allow me to choose any test runner besides unittests

### ISSUE THREAD

**Issue by boxed** [sixty-north/cosmic-ray#398]
```
> cosmic-ray new-config config.yml
[?] Top-level module: tri.struct
-- MENU: Test runner --
  (0) unittest
[?] Enter menu selection: pytest
[?] Enter menu selection:
```

This seems pretty broken.

**Comment by boxed** [comment]
I tried editing config.yml:

```
module: tri.struct

baseline: 10

exclude-modules:

test-runner:
  name: pytest
  args: 

execution-engine:
  name: local
```

But then when I try to run it I get 

```
cosmic-ray init config.yml my_session                               352ms  Sun Nov 18 14:58:31 2018
Traceback (most recent call last):
  File "/Users/boxed/Projects/tri.struct/venv/bin/cosmic-ray", line 11, in <module>
    sys.exit(main())
  File "/Users/boxed/Projects/tri.struct/venv/lib/python3.6/site-packages/cosmic_ray/cli.py", line 357, in main
    exit_at_end=False)
  File "/Users/boxed/Projects/tri.struct/venv/lib/python3.6/site-packages/docopt_subcommands/__init__.py", line 69, in main
    result = commands(argv)
  File "/Users/boxed/Projects/tri.struct/venv/lib/python3.6/site-packages/docopt_subcommands/subcommands.py", line 146, in __call__
    return handler(config)
  File "/Users/boxed/Projects/tri.struct/venv/lib/python3.6/site-packages/cosmic_ray/cli.py", line 51, in handle_baseline
    config['test-runner', 'args'])
  File "/Users/boxed/Projects/tri.struct/venv/lib/python3.6/site-packages/cosmic_ray/plugins.py", line 61, in get_test_runner
    on_load_failure_callback=_log_extension_loading_failure,
  File "/Users/boxed/Projects/tri.struct/venv/lib/python3.6/site-packages/stevedore/driver.py", line 61, in __init__
    warn_on_missing_entrypoint=warn_on_missing_entrypoint
  File "/Users/boxed/Projects/tri.struct/venv/lib/python3.6/site-packages/stevedore/named.py", line 89, in __init__
    self._init_plugins(extensions)
  File "/Users/boxed/Projects/tri.struct/venv/lib/python3.6/site-packages/stevedore/driver.py", line 113, in _init_plugins
    (self.namespace, name))
stevedore.exception.NoMatches: No 'cosmic_ray.test_runners' driver found, looking for 'pytest'
Error in subprocess
Command '['cosmic-ray', 'baseline', 'config.yml']' returned non-zero exit status 1.
```

**Comment by boxed** [comment]
```
> cosmic-ray --version
Cosmic Ray 3.2.0
```

**Comment by abingham** [comment]
It's a failure of documentation. You need to install the pytest test-runner plugin:
```
pip install cosmic-ray-pytest-runner
```
Let me know if that doesn't fix it, though.

**Comment by boxed** [comment]
Ah. Better, but now I get

```
> cosmic-ray init config.yml my_session
Operator provider load failure: extension-point="spor = cosmic_ray.interceptors.spor:intercept", err="No module named 'spor.repo'"
```

That seems pretty opaque, I don't know how to debug that.

**Comment by boxed** [comment]
Hmm.. could it be because I'm running the branch and not the main release?

**Comment by abingham** [comment]
Hmm. The spor interceptor should get installed by default (i.e. by the
top-level `setup.py`). What branch are you using?

**Comment by boxed** [comment]
Oh, my bad, that's me being confused. I am trying out mutpy and cosmic-ray in parallel so I'm just mixing them up. It's mutpy that has experimental pytest support in a branch :P

Ok, then I just install cosmic-ray via pip. Should I try the master branch you think?

**Comment by boxed** [comment]
Init seems to work with master.

**Comment by abingham** [comment]
> You really should add some kind of feedback when it's running, it looks like it's just hung.

I've been resistant to having CR print anything during exec; "silent on success" was beat into me at some point in my career. There have been [other discussions](https://github.com/sixty-north/cosmic-ray/issues/219) around this topic, so you're not the only person interested in it. I could probably be convinced to accept progress output from exec by default, with an option to make it quiet.

> But if you just release a new version so the one on PyPI isn't broken that seems like the biggest improvement. Followed shortly by the documentation fix discussed above.

3.3.0 should be available on PyPI now, and the [documentation has been updated](https://cosmic-ray.readthedocs.io/en/latest/installation.html).

> a bit silly: "if foo is not self" -> "if foo != self"

Yeah, there are a whole class of generally silly mutants that we could try filtering out. There was [some discussion of this already](https://github.com/sixty-north/cosmic-ray/issues/327), and I'm certainly not opposed to it on principle. 

> does that mean CR generated 141 mutants that it checked?

Yes, that's precisely what it means.  Though it's possible (but unlikely unless you intentionally asked for it) that some were skipped.

I've never spent much time on performance, so it doesn't surprise me that other tools are faster. As you say, the scaling/fan-out problem seems like a much more important piece of the puzzle.

> I'm curios about their higher order mutants stuff

I am too! We've had [some discussions](https://github.com/sixty-north/cosmic-ray/issues/296) about this in the past, and - given infinite time and money - I'd be delighted to support them in CR. 

Unfortunately, as you're probably gathering from our current pile of issues, I am not able to prioritize CR. I've been able to do a lot of good work on spor, and that directly benefits CR, but CR itself has been a bit lonely lately.

**Comment by rob-smallshire** [comment]
I'm going to hold out for the [https://www.linuxtopia.org/online_books/programming_books/art_of_unix_programming/ch11s09.html](Silence is Golden) Unix philosophy. You can get a progress report by sending SIGINFO (Ctrl-T) on macOS.

I'd be in favour of optionally turning progress reporting on with a verbose option.

**Comment by boxed** [comment]
You should try out mutmut which has some pretty verbose and (dare I say) pretty output when running. Just to get a feel for what it could be.

I've fairly recently rewritten mutmut to be based on a different AST lib: parso. That gives me full roundtrip ASTs, python2 and python3 support. It's also a big part of the secret sauce that means mutmut is ~1.1k lines. 

> As you say, the scaling/fan-out problem seems like a much more important piece of the puzzle.

And reuse of existing results. I've spent some time recently on this and I can safely say that working through mutants is super nice when it just runs your test suite on existing surviving mutants instead of everything. That's a much bigger win than parallelization, at least for small code bases, and if you are actually working to kill all mutants.

**Comment by boxed** [comment]
Heh, you could just rip out your mutation stuff and just use mutmuts. It's super tiny :P
