### ISSUE TITLE
Multiple PyPI entries for some plugins

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#399]
There seem to be multiple PyPI projects for the pytest test-runner plugin. First there's ours:

https://pypi.org/project/cosmic_ray_pytest_runner/

Then there's one by Pavel Zarubin:

https://pypi.org/project/cosmic-ray-pytest/

This second one points to what looks like an outdated clone of the original. It's a bit (ok, quite!) confusing to have both of them, and I think the second should be removed. It's not clear how to do this through official channels, though, so I need to figure out how to contact Pavel.

**Comment by abingham** [comment]
@pavel-one Are the the Pavel Zarubin who put up the `cosmic-ray-pytest` pypi entry?

**Comment by pavel-one** [comment]
@abingham no

**Comment by abingham** [comment]
Test runners are being phased out.
