### ISSUE TITLE
Init should refuse if there are existing results

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#417]
The init command should refuse to do anything if it sees any results in the session. We can provide a flag to the command that overrides this.

**Comment by muhd360** [comment]
@abingham can you pls link the respective file in this regards???

**Comment by abingham** [comment]
The command-line tool for `init` is implemented in `cosmic_ray.cli.init()`. I *think* all that we need to do is add a check if `database.num_results > 0`, refusing to continue if that's true. We could also add a command line option to allow initialization even in the presence of existing results, e.g.:
```
if database.num_results == 0 or force:
    cosmic_ray.commands.init(modules, database, operators_cfg)
``` 
Something like that.

**Comment by muhd360** [comment]
ok ill make the necessary changes and raise a pr can you pls assign the hacktoberfest label to this issue??

**Comment by muhd360** [comment]
hi @abingham a few follow up questions.
1.what is the test file in this scenario??
2. I understand --force will be a command in the cli .Since init expects only 2 args how can we pass force as a param???

**Comment by abingham** [comment]
1. You should add tests to tests/unittests/test_command_line_processing.py. We should have a test for both the positive and negative case, i.e. the existence or not of results.

2. You'll need to modify cli.init() to accept a 'force' argument, and add a new click option decorator for 'force'.

**Comment by muhd360** [comment]
hi @abingham im having build issues after using pyproject.toml to install the files and dependencies.Have i missed something????

**Comment by abingham** [comment]
You’ll need to give me more details than that. What’s failing?

**Comment by muhd360** [comment]
hi, i cant import the functions or the requirements.Its simply coming as module not found.I tried re-installing my virtual enviornment 2 times but still the issue wasn't fixed
![image](https://github.com/user-attachments/assets/aae3cd77-1538-4da2-b53e-42f12443112f)

**Comment by abingham** [comment]
I can only guess that your IDE is looking at a different virtual environment than the one you installed into. Can you check that they're the same environment?

**Comment by abingham** [comment]
Also, check that the pytest you're running is in the same venv as the code. If not, you might see similar errors. If you're not using uv to install Cosmic Ray, then you'll have to make sure to install pytest correctly yourself.

**Comment by muhd360** [comment]
what is uv??? forgive my ignorance

**Comment by muhd360** [comment]
hi i got it it was a vs code issue
