### ISSUE TITLE
_Py_HashRandomization_Init failure on Windows

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#435]
In virtual environments on Windows we see `Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python` for all test runs. This may be related to the use of `virtualenv` instead of `venv`.

This was first reported in #434 by @LLKoder

**Comment by LLKoder** [comment]
I still interest in CR project but I use Windows only and how I understand this bug not allow me correctly use CR in the wheeled package. Tell me please when can I approximately see a fixed bug?
I would try to fix this bug myself with pleasure, but unfortunately, I still have a little experience with Python.

**Comment by abingham** [comment]
I'm very close to a fix right now, I think. Hopefully in a day or two.

**Comment by abingham** [comment]
I think the remaining known windows issue - i.e. the inability to kill infinite loop subprocesses - is related to this: https://bugs.python.org/issue30154

**Comment by abingham** [comment]
@LLKoder You can try the `fix-windows-venvs` branch now. It seems to work with the exception that it can't kill mutants that go into an infinite loop. This seems to be because of problems with Python's subprocess module, and I'm looking at how to deal with this. But if your tests won't go into an infinite loop, then I think CR will work for you now.

**Comment by abingham** [comment]
I've resolved the issue of killing subprocesses that enter infinite loops. We are using asyncio's subprocess support, coupled with asynio timer support, to manage test subprocesses. It's not 100% polished yet, but it seems to work.

**Comment by abingham** [comment]
@LLKoder I've merged all of the changes for this into master. Please give it a try, and - if it works for you - close this issue. Thanks!

**Comment by LLKoder** [comment]
It's working without `-B`. No fatal errors. However, CR doesn't still correctly work. It seems it sees old cache files.
I'll send details by mail.

**Comment by abingham** [comment]
Please just post the details here. It's *much* easier for me to keep track of.

**Comment by LLKoder** [comment]
OK.
In the HTML report (example-session.html), you can see the strange behavior of CR's work. IMO some jobs are wrong.

6 : job ID d824a041742143649e5fbf8687667c1c
2**2=4
AssertionError: 1 != 4 - error (not 1, must be 4)
Test must be SURVIVED

11 : job ID 1162d67754f942d1a96558db8f6fe271
2^2=0
AssertionError: 2 != 4 - error (not 2, must be 0)
Test must be KILLED (It's right)

[tests.zip](https://github.com/sixty-north/cosmic-ray/files/3190664/tests.zip)

**Comment by abingham** [comment]
Try it now. I fixed a critical typo that was allowing pycs to be generated. Sorry about that.

**Comment by LLKoder** [comment]
All OK. It's working... Thanks a lot.

**Comment by LLKoder** [comment]
One question when can you update package for PyPI?

**Comment by abingham** [comment]
I pushed a new version yesterday that should include this change. Have you tried it? If it doesn't include this fix then I did something wrong.

**Comment by abingham** [comment]
I'll go ahead and close this issue. If there are problems with the PyPI distribution we can use a different issue to sort it out.
