### ISSUE TITLE
test-command {python-executable} Windows 10

### ISSUE THREAD

**Issue by LLKoder** [sixty-north/cosmic-ray#438]
If I set `test-command = "{python-executable} -m unittest discover"` in config I get a error in report:

```
'{python-executable}' is not recognized as an internal or external command,
operable program or batch file.
```

`test-command = "python -m unittest discover"` - all ok.

**Comment by abingham** [comment]
Right. We no longer do template replacement for commands. Does the documentation still say that we do? If do that needs to get fixed.

**Comment by LLKoder** [comment]
Ok. I have read [here](https://cosmic-ray.readthedocs.io/en/latest/quickstart.html#example-configuration), [here](https://cosmic-ray.readthedocs.io/en/latest/concepts.html#initializing-sessions) and [here](https://cosmic-ray.readthedocs.io/en/latest/concepts.html#test-commands).

**Comment by abingham** [comment]
Ok, sorry about that. For some reason, readthedocs doesn't always build the
latest versions of things, so you were seeing out-of-date docs.
