### ISSUE TITLE
cosmic-ray new config exit with an exception

### ISSUE THREAD

**Issue by drorasaf** [sixty-north/cosmic-ray#450]
If I follow the guide:
```
pip install cosmic_ray
cosmic-ray new-config config.toml
```
The output is:
```
Traceback (most recent call last):
  File "$USER/.local/bin/cosmic-ray", line 7, in <module>
    from cosmic_ray.cli import main
  File "$USER/.local/lib/python3.6/site-packages/cosmic_ray/cli.py", line 67, in <module>
    doc_template=DOC_TEMPLATE)
TypeError: __init__() got an unexpected keyword argument 'version'
```
Seems like it is unsynced with docopt commands, the moment I remove version from the constructor, I get other issues

**Comment by abingham** [comment]
Ah...I think the docopt-subcommands API has changed and we need to account
for that. The quickest solution, I think, would be to specify a version for
docopt-subcommands in our setup.py; we would just use the last version that
worked for cosmic ray.

**Comment by m4r35n357** [comment]
Me too

`$ cosmic-ray new-config config.toml
Traceback (most recent call last):
  File "/home/ian/.virtualenvs/gmpy2/bin/cosmic-ray", line 6, in <module>
    from cosmic_ray.cli import main
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/cosmic_ray/cli.py", line 67, in <module>
    doc_template=DOC_TEMPLATE)
TypeError: __init__() got an unexpected keyword argument 'version'
`

**Comment by abingham** [comment]
I've uploaded cosmic-ray-5.5.0 to pypi, so that should fix this. Let me know if it works for you now.

**Comment by m4r35n357** [comment]
Will do, thanks!

**Comment by m4r35n357** [comment]
I have now successfully completed the quickstart, thanks for fixing this!

**Comment by abingham** [comment]
No problem, and sorry for the delay. I have unfortunately not been able to give CR much attention lately.
