### ISSUE TITLE
Documentation on how to exclude modules and operators

### ISSUE THREAD

**Issue by Guillermo--** [sixty-north/cosmic-ray#455]
Hello! I haven't been able to find good documentation on how to exclude an entire module from being mutated. Same goes for excluding mutation operators that might not be relevant for my project.

For example, I have a `contants.py` that contains all the constants for my project, and I do not wish to include it as part of the mutation score.

Same for the `core/RemoveDecorator` operator. I'm not sure if it's a critical mutation for my project, so I'd like for it to be skipped for now.

**Comment by abingham** [comment]
You should be able to exclude a module from mutation via the `exclude-modules` entry in your config. 

There's currently no simple way to remove/skip a particular operator. You could remove `remove_decorator.RemoveDecorator` from `cosmic_ray.operator.provider._OPERATORS` and I think you'll get what you want, but obviously this is a short-term solution. You could also write a script that modifies your session to mark all `RemoveDecorator` entries as 'skipped' (I actually like this idea quite a bit...a tool for doing this kind of thing could be very powerful, and probably not too hard to write).

Unfortunately I'm slammed with high priority work right now and don't have much time for CR. I'll give you what help I can, though. I'm eager to see CR used!
