### ISSUE TITLE
Version 5.5.0 is available in Pypi, but this version is not in production branc (yet)

### ISSUE THREAD

**Issue by Alcolo47** [sixty-north/cosmic-ray#456]
The last stable version is today 5.1.0, but my pip install fetch 5.5.0

**Comment by abingham** [comment]
Are you sure? I see 5.5.0 in the `version.py` in `master` on github: https://github.com/sixty-north/cosmic-ray/blob/master/src/cosmic_ray/version.py

Maybe I misunderstand something though. Let me know if things still seem incorrect to you.

**Comment by Alcolo47** [comment]
But the release branch is on 5.1.0.
readthedoc consider this branch as v.stable and master as v.lastest (By looking for git commit hash at the end of doc) 

When i "pip install", I would like the stable ...

**Comment by abingham** [comment]
Ah right, sorry, I had forgotten about the "release" branch. I'll sort that out.

**Comment by abingham** [comment]
@Alcolo47 Is this resolved from your point of view? If so, feel free to close this. Thanks!
