### ISSUE TITLE
Investigate alternative "no mutate" pragma detection

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#467]
The pragma_no_mutate interceptor currently uses a regex to detect the pragma. This is mostly good, but is open for false-positives when e.g. the pragma is actually in a string literal (and should thus be ignored). This is a low-probability event, so we included the interceptor anyway, but it would be nice if we could find a detection method that was even better. This issue is to remind is to look into this.

This was initially discussed in PR #460

**Comment by Alcolo47** [comment]
PR https://github.com/sixty-north/cosmic-ray/pull/476 resolves that.
