### ISSUE TITLE
mutating order of operands

### ISSUE THREAD

**Issue by tomato42** [sixty-north/cosmic-ray#493]
for addition and multiplication, the order of operands doesn't matter (`a+b==b+a` – it's commutative), but for others, like subtraction, division, modulo, etc. the order is operands is important

is mutating the order of operands implemented?

(It would also be nice to change addition into division and then change order, but that's a probably a second-order mutation, and those are covered in #296)

**Comment by abingham** [comment]
This is not currently implemented, but it's not as trivial as it sounds. Addition is commutative for number types, but not for e.g. strings. Same with `*` when used as a repetition operator. So while this operator would be easy to implement insofar as swapping operands is simple, doing it in a way that is "smart" might not be possible...we can't generally ask a type of its operators are commutative.

**Comment by tomato42** [comment]
yes, but I'm not asking for doing the swap for operands that are sometimes commutative 

I'm asking for doing the swap for operands that are never commutative, like `%` or `//`

> we can't generally ask a type of its operators are commutative

can't we? what about type hinting?

**Comment by abingham** [comment]
> I'm asking for doing the swap for operands that are never commutative, like % or //

It's entirely possible (though perhaps perverse) for any operator to be commutative. Python can't guarantee that an arbitrary implementation of e.g. `__mod__` is not commutative.

> can't we? what about type hinting?

We could consider those, but that would only apply when they're available (and correct), which is not the general case.

I'm not opposed to this idea, but I want to make sure we've thought about the complications. I worry a great deal about adding operators which generate too many equivalents. I think you're right that swapping around operators like `%` and `//` will generally be OK.
