### ISSUE TITLE
cloning.py is using a deprecated virtualenv API

### ISSUE THREAD

**Issue by willfrey** [sixty-north/cosmic-ray#496]
I'm getting an AttributeError when running `cosmic-ray baseline ...` from [cloning.py#77](https://github.com/sixty-north/cosmic-ray/blob/master/src/cosmic_ray/cloning.py#L77)

```shell
AttributeError: module 'virtualenv' has no attribute 'create_environment'
```

After some investigating, it looks like `virtualenv` [made breaking changes with their major version release](https://github.com/pypa/virtualenv/issues/1585#issuecomment-584875029).

It also looks like `virtualenv.path_locations` is gone.

For what it's worth, I have `virtualenv==20.0.10` installed.

Thank you!

**Comment by abingham** [comment]
Thanks for letting me know! I'll sort that out soon.

**Comment by abingham** [comment]
@willfrey This should be fixed in [6.1.1](https://github.com/sixty-north/cosmic-ray/releases/tag/v6.1.1). I pinned the virtualenv version to less than 20.x. Could you test this out and let me know if it works for you?

**Comment by willfrey** [comment]
Giving it a whirl now!

**Comment by willfrey** [comment]
It worked! 👍

**Comment by abingham** [comment]
Awesome, thanks for checking. I'll close it out.
