### ISSUE TITLE
Removed dependency (spor)?

### ISSUE THREAD

**Issue by js-beaulieu** [sixty-north/cosmic-ray#497]
Hi,

Installing `cosmic-ray` is broken right now as it seems `spor` is not available on PyPI anymore. I couldn't find an issue regarding this for now, so I thought to raise the flag.

Here's a log from a broken CI run.
[Expected spor PyPI page](https://pypi.org/project/spor/)

```
24-Apr-2020 11:58:43 	  - Installing spor (1.1.3)
24-Apr-2020 11:58:44 	
24-Apr-2020 11:58:44 	[EnvCommandError]
24-Apr-2020 11:58:44 	Command ['/home/bamboo/.cache/pypoetry/virtualenvs/mobilelibrary-SI9WbxZK-py3.8/bin/pip', 'install', '--no-deps', 'spor==1.1.3'] errored with the following return code 1, and output: 
24-Apr-2020 11:58:44 	Collecting spor==1.1.3
24-Apr-2020 11:58:44 	  ERROR: Could not find a version that satisfies the requirement spor==1.1.3 (from versions: none)
24-Apr-2020 11:58:44 	ERROR: No matching distribution found for spor==1.1.3
```

**Comment by abingham** [comment]
Sorry about that! I'm reimplementing spor and prematurely removed the pypi package. I've put the package back on pypi, so things should work now.

**Comment by abingham** [comment]
@folkrav Does this work for you now?

**Comment by folkrav** [comment]
> @folkrav Does this work for you now?

I'll have to try this out Monday when I'm back at work. I'll make sure to update this ticket then.

**Comment by Karpov-Konstantin** [comment]
Hi!
Older versions are not supported now?
Spor is not available on PyPI again

**Comment by abingham** [comment]
@Karpov-Konstantin Sorry, I've put it back in place. The spor dependency has been removed from the trunk, but I forgot that the Python package needed to stay around for older versions.

**Comment by Karpov-Konstantin** [comment]
@abingham Thank you for the quick answer and for putting back the spor.
