### ISSUE TITLE
Problem running the unittests

### ISSUE THREAD

**Issue by lvdstam** [sixty-north/cosmic-ray#499]
I have forked the project and cloned it. Then:
- created a new virtual environment with python 3.7.6
- pip install -r requirements.txt
- pip install -e .[dev,test]

Then pytest fails with:
FAILED tests/test_suite/e2e/test_e2e.py::test_importing - FileNotFoundError: [Errno 2] No such file or directory: '/Users/310188215/PythonProjects/cosmic-ray/../example_project': '/Users/310188215/PythonProjects/cosmic-ray/../example_project'
FAILED tests/test_suite/e2e/test_e2e.py::test_empty___init__ - FileNotFoundError: [Errno 2] No such file or directory: '/Users/310188215/PythonProjects/cosmic-ray/../example_project': '/Users/310188215/PythonProjects/cosmic-ray/../example_project'
FAILED tests/test_suite/e2e/test_e2e.py::test_config_command - FileNotFoundError: [Errno 2] No such file or directory: '/Users/310188215/PythonProjects/cosmic-ray/../example_project': '/Users/310188215/PythonProjects/cosmic-ray/../example_project'
FAILED tests/test_suite/e2e/test_fast.py::test_fast_tests - FileNotFoundError: [Errno 2] No such file or directory: '/Users/310188215/PythonProjects/cosmic-ray/../fast_tests': '/Users/310188215/PythonProjects/cosmic-ray/../fast_tests'

I have retried with python 3.6.7 (which needed an export for click) but this gave the same result.

I'm running this on a mac.

Did I overlook something in setting up the environment?

**Comment by abingham** [comment]
The command for running the tests is `pytest tests/test_suite`. I've updated the docs to reflect this.

There should be no need to run `pip install -r requirements.txt`; `pip install -e .` is what you want.

**Comment by abingham** [comment]
There might still be some issues with the tests, but you'll get more better results if you use the command above.

**Comment by lvdstam** [comment]
Indeed this seems to give better results. Now two tests fail:
FAILED tests/test_suite/e2e/test_e2e.py::test_e2e[local-pytest] - subprocess.CalledProcessError: Command '['cr-filter-spor', '/private/var/folders/r0/dslm9dh57dv0k0t84hlrn7zc0000gn/T/pytest-of-310188215/pytest-12/test_e2e_local_pytest_0/cr-session.sqlite']' returned non-zero exit status 1.
FAILED tests/test_suite/e2e/test_e2e.py::test_e2e[local-unittest] - subprocess.CalledProcessError: Command '['cr-filter-spor', '/private/var/folders/r0/dslm9dh57dv0k0t84hlrn7zc0000gn/T/pytest-of-310188215/pytest-12/test_e2e_local_unittest_0/cr-session.sqlite']' returned non-zero exit status 1.

I will chack with python 3.7.6 also.

**Comment by abingham** [comment]
I've pushed a change that fixes this. The tests work on my system and on travis (except for a documentation issue). Try it now (and thanks for your patience).

**Comment by lvdstam** [comment]
All unittest now pass. Both on 3.7.6 and 3.6.7. haven't tried a newer python version.
