### ISSUE TITLE
Generate api docs dynamically

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#512]
Right now the sphinx-apidoc results are part of the repo, but there's no real reason for that. We should be able to generate those docs on demand whenever we build the sphinx project.

**Comment by drorasaf** [comment]
The idea is to stop including the output from sphinx-apidoc? but then there is less control over the docs and what exactly is set as docs

**Comment by abingham** [comment]
Actually, it looks like this might already be done. We used to store the sphinx build output in the repository itself, meaning it was built locally and committed. Now we use readthedocs, and it builds the docs whenever we make a commit. This latter approach is what I meant by this issue.

So I'm going to close this, but feel free to re-open it if you think there's anything to be done. Thanks for bringing this to my attention!
