### ISSUE TITLE
Proposed Documentation Changes

### ISSUE THREAD

**Issue by FloatingSunfish** [sixty-north/cosmic-ray#518]
I would like to propose the following Documentation changes to help make Cosmic Ray easier to use for users:

# `Init` Section

1. You should always run `init` whenever you make any production code and test changes.

2. You should always run `init` whenever you make changes to your configuration file. Fields that do not require `init` to be rerun should also be added to the documentation.

# Installation Section

1. Please link to the standard on how to install Python packages from source. Alternatively, please show the steps on how to do so.

# `cr-filter-operators` Section

1. Please state that regular expressions are optional, and provide examples for excluding operators both with and without regular expressions.

2. For the examples that include regular expressions, please provide a brief overview of how the regular expression is affecting the configuration.

# Miscellaneous

1. Note that even though Cosmic Ray is designed to be robust against user interrupts and crashes, it is good practice to **_always fully-check in a project_** before running mutation tests on it.

**Comment by abingham** [comment]
Thanks! I've pushed changes to address these.

**Comment by FloatingSunfish** [comment]
Thanks for adding these to the docs, @abingham!

I've reviewed the changes and they all look good.

However, I would like to propose the following change in the `init` section from:
Similarly, you need to create a new session with _init_ whenever your code-under-test changes.

To:
Similarly, you need to create a new session with _init_ whenever your code-under-test or test codes change.

Your thoughts?

**Comment by abingham** [comment]
That's a good point. I've updated the docs and pushed the change.
