### ISSUE TITLE
Excluded Mutation Operators Still Getting Run

### ISSUE THREAD

**Issue by FloatingSunfish** [sixty-north/cosmic-ray#522]
I have excluded the following mutation operators in my Cosmic Ray configuration file:
```
[cosmic-ray.filters.operators-filter]
exclude-operators = [
    "core/ReplaceComparisonOperator_Eq_Is",
    "core/ReplaceComparisonOperator_NotEq_IsNot"
]
```

I also reran `init` before running mutation tests.

However, when I ran an HTML report, the mutation operators were still getting run:

![1](https://user-images.githubusercontent.com/58676395/128292866-66802a61-616d-49a3-a16b-b3de8e83deac.PNG)
![2](https://user-images.githubusercontent.com/58676395/128292868-db3fc62c-04c9-415d-804e-9a312fa0fece.PNG)

**_NOTE:_** I tried a second time, this time running `cr-filter-operators mutation_test_session.sqlite` (which I assume isn't needed because the configuration file already has all the filters) after running `init` and it didn't solve the problem.

**Comment by abingham** [comment]
This features doesn't work right now. See #517.

**Comment by FloatingSunfish** [comment]
I see. From what I understood in [#517](https://github.com/sixty-north/cosmic-ray/issues/517), it was only excluding modules that didn't work, not excluding specific mutation operators.

Perhaps this belongs in its own issue?

**Comment by abingham** [comment]
Ah, you're right, sorry for not reading closely enough. I'll look into this.

**Comment by abingham** [comment]
The problem has to do with a mistake in how the filter operator is implemented. The `--config` option should actually be required, so you can fix your immediate issue by doing `cr-filters-operators --config <config file> mutation_test_session.sqlite`. I'll update the filter to require a config; it's currently optional because of a legacy way sessions used to work.

> which I assume isn't needed because the configuration file already has all the filters

It is required. Cosmic Ray doesn't run any filters on its own, and requires users to run them externally. We used to try to manage all of the filtering internally, and - while it's definitely technically possible - it was more trouble than it was worth.

**Comment by FloatingSunfish** [comment]
@abingham 
_>We used to try to manage all of the filtering internally_
By this, do you mean you tried just using the config file and no longer requiring users to run filter commands manually?

Also, thanks for the workaround while we wait for this issue to get resolved. 🙂

**Comment by abingham** [comment]
> By this, do you mean you tried just using the config file and no longer requiring users to run filter commands manually?

Correct. CR used to run certain kinds of filtering as part of the init phase, and it would read the filtering criteria from the config in the same way that e.g. `cr-filter-operators` does. But it added complexity to the implementation without adding sufficient benefits, i.e. it's very simple to run filters, add them to initialization scripts, or whatever.

**Comment by abingham** [comment]
This should be fixed in 8.3.3.

**Comment by FloatingSunfish** [comment]
@abingham 
Perhaps it would be a good idea to add a new section in the [**_`cr-filter-operators` documentation_**](https://cosmic-ray.readthedocs.io/en/latest/how-tos/filters.html?highlight=pragma#cr-filter-operators) like:

```
cr-filter-operators session.sqlite config.toml
```

Just to make it more uniform with `cr-filter-pragma` having an example.

**Comment by f4lcini** [comment]
I have Cosmic Ray version 8.4.1 and I keep having the same problem. exclude-operators does not filter out the unwanted operators.
Is there a solution or a bug fix for this situation?

**Comment by abingham** [comment]
No solution yet, I just need to find the time to do it.
