### ISSUE TITLE
virtualenv dependency conflicts.

### ISSUE THREAD

**Issue by dipudan** [sixty-north/cosmic-ray#537]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cosmic-ray 8.3.5 requires virtualenv<=16.7.10, but you have virtualenv 20.21.0 which is incompatible.

Cosmic-ray uses very old version of virtualenv and its causing conflicts with other modules which uses relatively newer versions.

**Comment by abingham** [comment]
I've pushed a version which doesn't have a dependency on `virtualenv`. It looks like this was a vestigial dependency! I'll close this issue, but please re-open it if your problem isn't fixed.

**Comment by abingham** [comment]
Yeah, there's some problem with the test suite on python 3.11. I'm pretty sure it's nothing you need to worry about if you just want to use CR. Hopefully I'll have it sorted out soon.

**Comment by dipudan** [comment]
Thank you Abingham, everything is working fine with the new version.
