### ISSUE TITLE
Figure out why CR falls over on hypothesis

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#77]
The [hypothesis](https://github.com/DRMacIver/hypothesis) package causes CR to fail in a strange way. It appears that we can't import certain of hypothesis' modules when we try to parse them.

Here's what we see:

```
% cosmic-ray hypothesis cosmic-ray/test_project/tests                                                ~/projects 
multiprocessing.pool.RemoteTraceback: 

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sixtynorth/projects/cosmic-ray/cosmic_ray/mutating.py", line 50, in run_with_mutant
    exec(code,  new_mod.__dict__)
  File "/Users/sixtynorth/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/hypothesis-1.2.1-py3.4.egg/hypothesis/utils/show.py", line 19, in <module>
    import hypothesis.internal.reflection as reflection
  File "/Users/sixtynorth/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/hypothesis-1.2.1-py3.4.egg/hypothesis/__init__.py", line 21, in <module>
    from hypothesis.searchstrategy import strategy
  File "/Users/sixtynorth/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/hypothesis-1.2.1-py3.4.egg/hypothesis/searchstrategy/__init__.py", line 22, in <module>
    from . import numbers as s1
  File "/Users/sixtynorth/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/hypothesis-1.2.1-py3.4.egg/hypothesis/searchstrategy/numbers.py", line 26, in <module>
    from hypothesis.searchstrategy.misc import SampledFromStrategy
  File "/Users/sixtynorth/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/hypothesis-1.2.1-py3.4.egg/hypothesis/searchstrategy/misc.py", line 20, in <module>
    from hypothesis.types import RandomWithSeed
  File "/Users/sixtynorth/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/hypothesis-1.2.1-py3.4.egg/hypothesis/types.py", line 21, in <module>
    from hypothesis.utils.show import show
ImportError: cannot import name 'show'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sixtynorth/.virtualenvs/cosmic-ray/bin/cosmic-ray", line 9, in <module>
    load_entry_point('cosmic-ray==0.0.0', 'console_scripts', 'cosmic-ray')()
  File "/Users/sixtynorth/projects/cosmic-ray/cosmic_ray/app.py", line 105, in main
    for mutation_record, test_result in results:
  File "/Users/sixtynorth/projects/cosmic-ray/cosmic_ray/app.py", line 63, in hunt
    result = async_result.get(timeout=timeout)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
ImportError: cannot import name 'show'
```

---
- Bitbucket: https://bitbucket.org/austin_bingham/cosmic-ray/issue/26
- Originally reported by: [austin_bingham](http://bitbucket.org/austin_bingham)
- Originally created at: 2015-04-16T19:15:51.478

**Comment by abingham** [comment]
@DRMaciver FYI

**Comment by DRMacIver** [comment]
A thing worth noting is that Hypothesis has a separate src/ directory, so if you're searching relative to . then the files won't be found. I believe I produced that exception both when running with a setup.py develop and with src on the PYTHONPATH.

**Comment by DRMacIver** [comment]
Oh another thing possibly worth noting is that show is not, as it might appear from usage, a function. It's in fact a top level object definition of the form show = ExtMethod(). So if you have e.g. a delete assignment mutation it's not surprising that that would sometimes fail.

**Comment by abingham** [comment]
This issue is still a bit mysterious. It doesn't seem to be related to specific mutation operators, and I haven't had any luck creating a minimal program that replicates it. My current guess is that it's some `multiprocessing` oddity. I should have some time to dedicate to this soon, I hope.

**Comment by DRMacIver** [comment]
^^ the above seems to be a minimal example of this problem. It's something to do do about when types become visible when you've got recursive dependencies in the module graph. However it's something more complicated than that - note that deleting stuff from Stream makes it go away.

**Comment by DRMacIver** [comment]
I was bored and thought I'd try to minimize something for this. Here's a shrunk version of cosmic ray that errors in the same way on this program: https://gist.github.com/DRMacIver/6317c708a6adae0059c0

I think the problem is the way you're overwriting sys.modules in run\_with\_mutant. The error goes away if I comment out the sys.modules\[module\_name\] = new\_mod, though it's unclear what *does* happen then as I've already minimized it a bit too far for it to be clear what's actually going on :-)

**Comment by abingham** [comment]
I haven't had much time to look at this yet, but I think you're correct about the circular import dependency being an issue. That at least smells a bit fishy. In any event, I'm probably misusing `sys.modules` in some subtle (or not so subtle) way that's breaking the assumptions that allow your module to load under normal conditions.

What I can try is to implement a proper `Finder` and `Loader` and see if that fixes things. Fortunately these are pretty straightforward to make, and in fact I think I can just re-appropriate some from the history of CR. This feels like "The Right Thing To Do" anyway.

**Comment by DRMacIver** [comment]
Note that the reason the module can load under normal circumstances is not precisely because it has a circular dependency that happens to work. What happens is that loading hypothesis.types forces the hypothesis.__init__ module to load first. There's no actual circular dependency, just an unexpected load order.

And don't worry about not having had time to look into it. My doing so should not in any way being taken as a nag that you should. :-)

**Comment by abingham** [comment]
It's probably premature to declare victory, but commit 2cd072b998db31b389a493b1e5f6fdc2ac1b0807 seems to be successfully mutating and executing the hypothesis codebase.

**Comment by abingham** [comment]
Err...scratch that. The situation certainly looks better now, but it appears that there are still some import-related issues.

**Comment by DRMacIver** [comment]
So I'm trying running master cosmic-ray against master hypothesis as:

````bash
PYTHONPATH=src cosmic-ray hypothesis tests/test_descriptortests.py
````

I'm getting lots of output like the following:

```
Start directory is not importable: 'tests/test_descriptortests.py'
Outcome.INCOMPETENT -> replace Eq with NotEq @ /home/david/projects/hypothesis/src/hypothesis/strategytests.py:<UNKNOWN>
Start directory is not importable: 'tests/test_descriptortests.py'
```
Is this WAI, user error on my part, or a bug?

**Comment by DRMacIver** [comment]
Ah OK.

**Comment by abingham** [comment]
At least for now, you can't specify a test file like that (i.e. `tests/test_descriptortests.py`). CR expects a directory, and it passes that into [unittest.TestLoader.discover](https://docs.python.org/3/library/unittest.html#unittest.TestLoader.discover). That function also takes a file pattern, so it should be fairly straightforward to let you specify single files as well.

**Comment by DRMacIver** [comment]
Ah, I see. 

It now seems to be running against Hypothesis. I sure wish I could tell it that it won't find anything interesting to do flipping things in the show module though.

**Comment by DRMacIver** [comment]
(It would also be nice to be able to suppress stdout from the run process, but that's due to Hypothesis specific quirks)

**Comment by abingham** [comment]
I've made [an issue](https://github.com/sixty-north/cosmic-ray/issues/105) to let you tell CR to skip certain modules.

**Comment by DRMacIver** [comment]
Thanks! :heart:

**Comment by abingham** [comment]
The import-related issues I was seeing earlier had to do with the way I was scanning the `tests` package. I was instructing `unittest` to discover tests in the `tests` directory, so it was not treating that directory as a package. As a result, the relative imports in the `tests` package were failing with diagnostics like this:
```
  File "/Users/sixtynorth/projects/hypothesis/tests/test_basic_strategy.py", line 27, in <module>\n    from .test_example_quality import minimal\nSystemError: Parent module \'\' not loaded, cannot perform relative import
```
If I run discovery on the parent directory of `tests`, however, things seem to work much better!

**Comment by LLKoder** [comment]
I use hypothesis 4.23.5 and have the same problem in Windows 10. When I run CR with my test I have an error in the report:
```
======================================================================
ERROR: tests.test_app (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_app
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\Lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\Lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Users\...\AppData\Local\Temp\tmpb3b7zi6s\repo\tests\test_app.py", line 5, in <module>
    from hypothesis import given
ModuleNotFoundError: No module named 'hypothesis'
```

**Comment by abingham** [comment]
Are you installing hypothesis in your clone commands? CR can't guess what dependencies your tests have.

**Comment by LLKoder** [comment]
> Are you installing hypothesis in your clone commands? 

What do you mean? I installed the hypothesis as the module.

> CR can't guess what dependencies your tests have.

Can I tell CR that I use hypothesis either?

**Comment by abingham** [comment]
Before Cosmic Ray does any mutations, it makes one or more copies of your code along with a new virtual environment for each copy. But CR doesn't know anything about what to install into these environments. You need to tell it everything that it needs to do to properly set up these environments so that it can run your tests. You do this with the `cosmic-ray.cloning.commands` section of the configuration.

So for example, if you need to:
- install your package with `setup.py`
- install pytest
- install hypothesis

you would need something like this:
```
[cosmic-ray.cloning]
commands = [
    "pip install .",
    "pip install pytest",
    "pip install hypothesis"
]
```

This is (lightly) covered [in the docs](https://cosmic-ray.readthedocs.io/en/latest/cloning.html#commands).

**Comment by LLKoder** [comment]
Thanks a lot for the explanation. Just I have not understood what is this functional for.

**Comment by abingham** [comment]
The documentation could definitely use some improvement, and I apologize
for the current state of things. I hope everything is working for you now!
