### ISSUE TITLE
Add support for py.test

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#79]
The hypothesis project would like this.

----------------------------------------
- Bitbucket: https://bitbucket.org/austin_bingham/cosmic-ray/issue/24
- Originally reported by: [austin_bingham](http://bitbucket.org/austin_bingham)
- Originally created at: 2015-04-16T12:00:46.048

**Comment by jonafato** [comment]
Is this a duplicate (more specifically, a subset) of #99, or are there py.test-specific features that would not fall under that other issue?

**Comment by abingham** [comment]
Yes, this one is subset of #99. The issue list is a it of a mish-mash of real issues and notes to myself.

**Comment by nilp0inter** [comment]
+1 for this one :)

**Comment by abingham** [comment]
I guess this means I need to learn py.test ;)

**Comment by abingham** [comment]
I've added rudimentary support for pytest. You can use it like this:
```
cosmic-ray run --test-runner=pytest <module to test> <test directory>
```
I've only used to run `unittest`-based tests, so perhaps it's missing important features. If you have time, try it out and let me know how it goes!

**Comment by nilp0inter** [comment]
Sweet! I'll give it a try tomorrow.

Thank you!

**Comment by nilp0inter** [comment]
It looks great! I'm looking forward to see this feature in the stable version.

**Comment by abingham** [comment]
@nilp0inter I've merged this into the main branch, so it's ready for use. Kick the tires a bit and let me know if you run into any problems.
