### ISSUE TITLE
Create executable package

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#95]
Just a simple **main**.py to kick off main processing.

---
- Bitbucket: https://bitbucket.org/austin_bingham/cosmic-ray/issue/9
- Originally reported by: [austin_bingham](http://bitbucket.org/austin_bingham)
- Originally created at: 2015-02-04T13:02:06.457

**Comment by drorasaf** [comment]
I think this issue is covered no?

**Comment by abingham** [comment]
yeah, I think this is unnecessary now. It probably wasn't really necessary back when I wrote it :) Our command line tools are in pretty good shape, I think.
